### ISSUE TITLE
Incompatible with rxmongo `0.11.10`

### ISSUE THREAD

**Issue by scullxbones** [scullxbones/akka-persistence-mongo#105]
Something internally must have changed, it's not enough to be source compatible.

**Comment by marcuslinke** [comment]
@scullxbones Do you have any idea whats the problem here?

**Comment by scullxbones** [comment]
@gbrd detailed a little bit the problems he had in the gitter channel (https://gitter.im/scullxbones/akka-persistence-mongo).  The tests do not pass with this version of reactive mongo, but in a non-reproducible way.  It may be how the disconnect / retry logic works now?  All I know is that driver is extremely difficult to support on any range of versions, because things are changing so quickly in backward-incompatible ways.  I had similar problems earlier when the max version the plugin supported was `0.11.8` I believe.  Casbah is so much more stable, I was able to support a major version change from 2.x to 3.x with no additional changes in the plugin.

**Comment by tmbo** [comment]
@scullxbones is there any update on the rxmongo front?

**Comment by scullxbones** [comment]
@tmbo no, I haven't delved back into this recently.  Getting burned several times by backward/forward incompatibilities gave me a reason to pause and let that project settle down a bit.  One thing I can't support is versioning the plugin for (almost) every rxmongo point release.

Took a few minutes to check out the latest release, I see there are still no convenient release notes.  I need to review commit logs to see what's changing, will take a look later today and see if anything pops out.

Is there a specific version of rxmongo you need to use?

**Comment by tmbo** [comment]
I just updated our application to the latest version `0.11.13` which worked quite well.

**Comment by tmbo** [comment]
Yes, but I haven't tried the akka-persistence yet, since I noticed this bug. So for the rest of our app the transition to the newer rxmongo version was smooth, but I guess you are using some more advanced features.

**Comment by tmbo** [comment]
Let me know if there is anything I can help you with.

**Comment by scullxbones** [comment]
@tmbo re: help, it would be helpful to hear back on how your akka-persistence plugin testing goes

**Comment by misamae** [comment]
I have a project with reactivemongo 0.11.14 and play 2.5 running. My prototype for using your mongodb driver works well. I was wondering if there is any update or progress regarding fixing the bug for latest version of reactivemong. Thanks.

**Comment by scullxbones** [comment]
Hi @misamae, I don't have any updates.  This ticket isn't actively being worked on at the moment.

**Comment by misamae** [comment]
Thanks @scullxbones. I cloned the project see if can build it. Are there any instruction how to build the package. I simple did sbt package. but I dont see any packages. My apology if this is not related to this issue. But I couldn't find the right place to ask this question.

**Comment by scullxbones** [comment]
You're right, there are no instructions on how to build the package, but `sbt package` should do it.  That will create jar files in each of the `target/scala_2.11` sub-directories - `common`, `casbah`, `rxmongo`.

**Comment by misamae** [comment]
thanks @scullxbones. That's what I did. I get the following error. 

UNRESOLVED DEPENDENCIES 
com.github.scullxbones#akka-persistence-mongo-common_2.11;1.3.0: configuration not public in com.github.scullxbones#akka-persistence-mongo-common_2.11;1.3.0: 'test'. It was required from com.github.scullxbones#akka-persistence-mongo-rxmongo_2.11;1.3.0 test

My apology again for asking here.

**Comment by scullxbones** [comment]
I'm not seeing that locally, for whatever that's worth.  A little bit of research on the web makes me think that it may help to try a local publish.

**Comment by misamae** [comment]
Thanks @scullxbones. It is possible that my .ivy repository is somehow corrupted. However, I created a separate project and managed to package rxmongo project. I upgraded the reactive mongo to 0.11.14 and added it my project. It works with no changes. PersistentActors now write to the journal. I haven't tested ReadJournal yet.

**Comment by scullxbones** [comment]
If I remember correctly, the issue with rxmongo 0.11.10+ was more around the edge cases than anything else.  The test suite would fail in strange ways for example.  It may work for regular usage most of the time.

**Comment by misamae** [comment]
Thanks @scullxbones . the problem I had was that during initialisation of the actor, the system was complaining that a method that was related to Index Manger in rxmongo driver didn't exists.

**Comment by scullxbones** [comment]
Ah.  Yeah, ok.  Backward incompatibilities.

So need a new release of plugin to support `0.11.14`...

**Comment by scullxbones** [comment]
Fixed in `1.3.3`

**Comment by marcuslinke** [comment]
Great news! Thanks @scullxbones

**Comment by scullxbones** [comment]
Scratch that, ignore `1.3.3` - use `1.3.4`

**Comment by misamae** [comment]
Thanks.
