### ISSUE TITLE
v1.2.2: rxmongo - Missing journal index for field `to`

### ISSUE THREAD

**Issue by marcuslinke** [scullxbones/akka-persistence-mongo#110]
Coming from v0.4.1 of the plugin after migrating to new journal scheme there is a problem to recover an actor when it has massive events persisted.

```
2016-04-12 15:24:01,195 [error] - application - Receivers recovery failure: proceed with recovering
reactivemongo.core.errors.DetailedDatabaseException: DatabaseException['Runner error: Overflow sort stage buffered data usage of 33554599 bytes exceeds internal limit of 33554432 bytes' (code = 17144)]
```

I guess this is related to this query: https://github.com/scullxbones/akka-persistence-mongo/blob/master/rxmongo/src/main/scala/akka/contrib/persistence/mongodb/RxMongoReadJournaller.scala#L192

Adding an index manually 
```
{"to": 1}
```

solved the problem.

**Comment by scullxbones** [comment]
Yuck, the old sort-huge-query-in-memory error.  That is surprising, I thought there were indices that included both the `pid` and the `to` that should support the sorted query.

So i'm sure what you're saying - by recover you mean what runs at persistent actor startup before it begins accepting new messages?  Any idea how many events this particular actor needed to replay?

**Comment by marcuslinke** [comment]
Right, this occurs while recovering the actor state without any snapshots involved by replaying all approx. 250.000 events stored in the journal. There is already an index `max_sequence_sort` but it seems to me it has the wrong sort order for `to`:
```
{
    "pid" : 1,
    "to" : -1
}
```

**Comment by marcuslinke** [comment]
Hmmm. Could'nt reproduce it again. Now it works without the additional index. Sorry for confusion!
