### ISSUE TITLE
v.1.2.2 - rxmongo: Journal replay OutOfMemoryException

### ISSUE THREAD

**Issue by marcuslinke** [scullxbones/akka-persistence-mongo#111]
Journal replay loads all events into memory before passing it to the PersistentActor. This leads to an OutOfMemoryException when having a huge amount of events.

The called `journalRange` function uses `Iteratee.getChunks[Event])` internally which may blow up the memory.

**Comment by scullxbones** [comment]
Yeah that's not good - and there's no reason to use `getChunks` that I can think of.  @marcuslinke you're finding all the super-big journal bugs.  Thanks!

**Comment by marcuslinke** [comment]
@scullxbones I will file a PR soon.

**Comment by scullxbones** [comment]
Closed by #112

**Comment by scullxbones** [comment]
Released with `1.2.3` - thanks @marcuslinke!

**Comment by marcuslinke** [comment]
@scullxbones Cool!
