### ISSUE TITLE
v1.2.3: MongoReadJournal.eventsByPersistenceId doesn't respect sequence number limits

### ISSUE THREAD

**Issue by marcuslinke** [scullxbones/akka-persistence-mongo#113]
@scullxbones It seems to me that `realtimeSource` doesn't respect sequence number limits `fromSequenceNr` and `toSequenceNr` here:

https://github.com/scullxbones/akka-persistence-mongo/blob/master/common/src/main/scala/akka/contrib/persistence/mongodb/MongoReadJournal.scala#L61

This leads to duplicate key exceptions in my specific view implementation.

**Comment by marcuslinke** [comment]
Additionally the choosen buffer size of 100 should be increased for high volumes. There were some events missing in my view and I suspect this to be the reason. Maybe the value should be configurable?

**Comment by marcuslinke** [comment]
@scullxbones Changing buffer size shows no effect. Please ignore the latest comment in favor of https://github.com/scullxbones/akka-persistence-mongo/issues/114

**Comment by scullxbones** [comment]
@marcuslinke wow - agreed, those parameters are ignored.

**Comment by scullxbones** [comment]
I've got a fix locally, will add to your PR for `1.2.4`

**Comment by scullxbones** [comment]
This one is available in `1.2.4` also, thanks for the report and using the plugin!
