### ISSUE TITLE
1.2.4: rxmongo - realtime views may receive events that are not persisted in the journal

### ISSUE THREAD

**Issue by marcuslinke** [scullxbones/akka-persistence-mongo#116]
See https://github.com/scullxbones/akka-persistence-mongo/commit/83d95e2d91b3107872bdeb6bf645a1f046cb6b22#diff-1c8129596ef4481b535c346cd14bd6cbR73

**Comment by scullxbones** [comment]
Fixed in `1.2.5`

**Comment by marcuslinke** [comment]
@scullxbones Thanks!
