### ISSUE TITLE
Rx version throws exception in conjuction with  sharding 

### ISSUE THREAD

**Issue by JurajBurian** [scullxbones/akka-persistence-mongo#126]
Hi folks, 
**the problem :** no such method exception occurred (see text below)
environment: Akka 2.4.9, reactive mongo 0.11.14,sharding used
_Workaround:_ 
When I recompiled library against latest driver, problem disappeared.

Can anybody help me and release version compiled again latest (0.11.14) reactive mongo driver ?
Many times thank you .

p.s. later we can find the roots of the problem

**exception:**
Uncaught error from thread [application-akka-contrib-persistence-dispatcher-21] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[application]
java.lang.NoSuchMethodError: reactivemongo.api.indexes.Index$.$lessinit$greater$default$8()Lreactivemongo/bson/BSONDocument;
        at akka.contrib.persistence.mongodb.RxMongoSnapshotter.snaps(RxMongoSnapshotter.scala:60)
        at akka.contrib.persistence.mongodb.RxMongoSnapshotter.findYoungestSnapshotByMaxSequence(RxMongoSnapshotter.scala:26)
        at akka.contrib.persistence.mongodb.RxMongoPersistenceExtension$Configured$$anon$2.akka$contrib$persistence$mongodb$MongoPersistenceSnapshotFailFast$$super$findYoungestSnapshotByMaxSequence(RxMongoPersistenceExtension.scala:243)

**Comment by scullxbones** [comment]
Hi @JurajBurian,

This version of rxmongo is currently unsupported as documented [here](https://github.com/scullxbones/akka-persistence-mongo/blob/master/docs/akka24.md) in the reactive mongo section.  It's not backward compatible to older versions that are supported (`0.11.9`).  

There is a PR where i'm working through the changes needed to support `0.11.14` #123 - the problem tends to not show up immediately, but there are race conditions still that definitely cause tests to fail *most* of the time.  I can't release that code yet.

Also see issue #105 for previous discussion.

**Comment by scullxbones** [comment]
Version `1.3.3` was just released - it should be compatible with `0.11.14`

**Comment by scullxbones** [comment]
Ugh.  `1.3.4` actually has fix in it.  Apologies.

**Comment by JurajBurian** [comment]
Thank you @scullxbones.
