### ISSUE TITLE
Support for reactive mongo 0.12.0

### ISSUE THREAD

**Issue by stevejagodzinski** [scullxbones/akka-persistence-mongo#128]
Requesting support for version 0.12.0

http://reactivemongo.org/releases/0.12/documentation/release-details.html

**Comment by alari** [comment]
0.12 is preparing to cross-compile to scala 2.12: https://github.com/ReactiveMongo/ReactiveMongo/pull/601
0.11 probably won't be

**Comment by alari** [comment]
@scullxbones do you have plans to add support for 0.12 and Scala 2.12? Can I help?

**Comment by scullxbones** [comment]
@alari yep definitely want to support scala 2.12.  If that means rxmongo goes to 0.12, i'm fine with that.  I'd be happy for help with a PR if you have time.

**Comment by scullxbones** [comment]
Tagging #133

**Comment by terryhendrix** [comment]
Our project needs this as well. When deletingEvents, we get java.lang.NoClassDefFoundError: reactivemongo/api/commands/AggregationFramework$Max.

We want to use reactive-mongo 0.12.1

**Comment by scullxbones** [comment]
FYI still working on this - things are mostly working, but found an issue on read journal sorting that needs solved before release.

**Comment by scullxbones** [comment]
Fixed in `1.4.0`
