### ISSUE TITLE
Missing serializer id from the payload

### ISSUE THREAD

**Issue by filosganga** [scullxbones/akka-persistence-mongo#137]
The serialized payload misses the serializer identification in the journal collection. It is needed to deserialize properly an event.

The akka-serialization, when serializing an instance `o`, calls
```
serializerFor(o.getClass)
``` 

During the deserialization instead it should call this: 
```
  deserialize(bytes, serializerIdentifier, manifestOrClass)
```

It is because the original class and the class we want to deserialize to may be different. Also it allows to evolve the schema.

At the moment the plugin does not allow it, as it always use the HINT field even if the serializer has written the SER_MANIFEST as a string.

**Comment by scullxbones** [comment]
Fixed in `1.3.7`, thanks!
