### ISSUE TITLE
Looking for a working example

### ISSUE THREAD

**Issue by dmassart** [scullxbones/akka-persistence-mongo#140]
I am not reporting an issue, but rather asking for help. I am using the following test:

    import akka.actor._
    import akka.persistence._

    class Counter extends PersistentActor with ActorLogging {

        import Counter._

        override def persistenceId: String = "counter"
        var state: State = new State( 0 )

        override def receiveRecover: Receive = 
        {
            case RecoveryCompleted => {
                println( "Recovery completed." )
            }
            case SnapshotOffer( _, snapshot: State ) => {
                state = snapshot
            }
            case op: Operation => {
                updateState( op )
            }
        }

        override def receiveCommand: Receive = 
        {
            case op: Operation => {
                println( s"Counter receive ${op}" )
                persist( op ) 
                {
                    op => updateState( op )
                }
            }
        
            case "print" => {
                println(s"counter's current state: ${state}")
            }
    
            case SaveSnapshotFailure( _, reason ) => {
                println( s"save snapshot failed, reason: ${reason}" )
            }
        
            case SaveSnapshotSuccess( _ ) => {
                println(s"snapshot saved")
            }
        }
    
        def updateState( op: Operation ): Unit = {
            op match {
                case Increment( n ) => {
                    state = state.inc( n )
                    takeSnapshot
                }
    
                case Decrement( n ) => {
                    state = state.dec( n )
                    takeSnapshot
                }
            }
        }
    
        def takeSnapshot: Unit = 
        {
            saveSnapshot( state )
        }
    }

    object Counter 
    {
        sealed trait Operation 
        {
            val count: Int
        }

        case class Increment(override val count: Int) extends Operation

        case class Decrement(override val count: Int) extends Operation

        final case class State( n: Int ) 
        {
            def inc(x: Int) = 
            {
                State( n + x )
            }
        
            def dec( x: Int ) = 
            {
                State( n - x )
            }
        }
    }
    
    object PersistenceDemo
    {
        import akka.util.Timeout
        import scala.concurrent.duration._
        import akka.pattern.ask
        import akka.dispatch.ExecutionContexts._
        implicit val ec = global
    
        def main(args: Array[String]) 
        {
            import Counter._

            val system = ActorSystem("persistent-actors")
            val counter = system.actorOf(Props[Counter], "counter")

            counter ! Increment(3)
            counter ! Increment(5)
            counter ! Decrement(3)
            counter ! "print"

            Thread.sleep(10000)
            system.terminate()
        }
    }

The example works well when used with the following config file:

    akka {
	persistence {
    	journal {
      		plugin = "akka.persistence.journal.leveldb",
      		leveldb {
        		dir = "target/example/journal",
        		native = false
      		}
    	},
    	snapshot-store {
      		plugin = "akka.persistence.snapshot-store.local",
      		local {
        		dir = "target/example/snapshots"
      		}
  	}
    }

Then I try to use akka-persistence-mongo with the rxmongo driver  by replacing the config by the following:

    akka { 
        persistence {
    	    journal {
    		plugin = "akka-contrib-mongodb-persistence-journal"
    		leveldb.native = false
    	}
    	snapshot-store {
    		plugin = "akka-contrib-mongodb-persistence-snapshot"
    	}
    }
    
    contrib {
    	persistence.mongodb {
    		mongo {
    			mongouri = "mongodb://localhost:27017/akka-persistence"
    			journal-collection = "journal"
    			journal-index = "journal_index"
    			snaps-collection = "snapshots"
    			snaps-index = "snaps_index"
    			journal-write-concern = "Acknowledged"
    			#use-legacy-serialization = false
    		}
    	    }
        }
    }

Using the following dependencies:

    scalaVersion := "2.11.8"
    lazy val akkaVersion = "2.4.16"

    // Akka Actor
    libraryDependencies += "com.typesafe.akka" % "akka-actor_2.11" % akkaVersion

    // Akka sl4j (logging)
    libraryDependencies += "com.typesafe.akka" % "akka-slf4j_2.11" % akkaVersion
    libraryDependencies += "org.slf4j" % "slf4j-simple" % "1.7.22"

    // Akka Persistence
    libraryDependencies += "com.typesafe.akka" % "akka-persistence_2.11" % akkaVersion
    // On file system
    //libraryDependencies += "org.iq80.leveldb"            % "leveldb"          % "0.7"
    //libraryDependencies += "org.fusesource.leveldbjni"   % "leveldbjni-all"   % "1.8"
    // In MongoDB using the reactive mongo driver
    libraryDependencies += "com.github.scullxbones" % "akka-persistence-mongo-rxmongo_2.11" % "1.3.7"
    
    // reactive mongo
    libraryDependencies += "org.reactivemongo" % "play2-reactivemongo_2.11" % "0.11.14"

When I run the example, I get the following:

[info] Running PersistenceDemo
[DEBUG] [01/31/2017 14:29:37.542] [run-main-0] [EventStream(akka://persistent-actors)] logger log1-Logging$DefaultLogger started
[DEBUG] [01/31/2017 14:29:37.545] [run-main-0] [EventStream(akka://persistent-actors)] Default Loggers started
[DEBUG] [01/31/2017 14:29:37.577] [persistent-actors-akka.actor.default-dispatcher-4] [akka.persistence.Persistence(akka://persistent-actors)] Create plugin: akka-contrib-mongodb-persistence-journal akka.contrib.persistence.mongodb.MongoJournal
[DEBUG] [01/31/2017 14:29:37.613] [persistent-actors-akka.actor.default-dispatcher-4] [akka.persistence.Persistence(akka://persistent-actors)] Create plugin: akka-contrib-mongodb-persistence-snapshot akka.contrib.persistence.mongodb.MongoSnapshots
[persistent-actors-akka-contrib-persistence-dispatcher-6] INFO reactivemongo.api.MongoDriver - No mongo-async-driver configuration found
[persistent-actors-akka-contrib-persistence-dispatcher-6] INFO reactivemongo.api.MongoDriver - [Supervisor-1] Creating connection: Connection-2
[persistent-actors-akka-contrib-persistence-dispatcher-12] INFO reactivemongo.api.MongoDriver - [Supervisor-1] Creating connection: Connection-3
Recovery completed.
Counter receive Increment(3)
[DEBUG] [01/31/2017 14:29:39.529] [persistent-actors-akka-contrib-persistence-dispatcher-6] [akka.serialization.Serialization(akka://persistent-actors)] Using serializer[akka.serialization.JavaSerializer] for message [Counter$Increment]
[ERROR] [01/31/2017 14:29:39.660] [persistent-actors-akka.actor.default-dispatcher-2] [akka://persistent-actors/user/counter] Failed to persist event type [Counter$Increment] with sequence number [1] for persistenceId [counter]. (reactivemongo.api.commands.LastError)

And indeed, when checking mongoDB, only the first state is persisted

{
	"_id" : ObjectId("5890949e0dc3d42c8c7ad8d2"),
	"pid" : "counter",
	"from" : NumberLong(1),
	"to" : NumberLong(1),
	"events" : [
		{
			"v" : 1,
			"pid" : "counter",
			"sn" : NumberLong(1),
			"_t" : "ser",
			"p" : BinData(0,"rO0ABXNyABFDb3VudGVyJEluY3JlbWVudC2LomelbfVyAgABSQAFY291bnR4cAAAAAM="),
			"_h" : "Counter$Increment",
			"_si" : 1,
			"_w" : "114f52e4-6824-45a7-9f7e-a61145e5cc1e"
		}
	],
	"v" : 1
}

Any hint about what I do wrong is very welcome.

**Comment by scullxbones** [comment]
Hi @dmassart 

Hmm, this is not an especially helpful message from the plugin:

```
[ERROR] [01/31/2017 14:29:39.660] [persistent-actors-akka.actor.default-dispatcher-2] [akka://persistent-actors/user/counter] Failed to persist event type [Counter$Increment] with sequence number [1] for persistenceId [counter]. (reactivemongo.api.commands.LastError)
```

Given the rest of the logging looks reasonable and you get one record in mongodb tells me things are mostly correct.  I'll have to see if I can duplicate locally.

**Comment by scullxbones** [comment]
So I added what I think the test case was - and I'm not seeing any issues, the demo main runs without error, entries are made in the journal, etc.

@dmassart can you take a look at [scullxbones/akka-persistence-mongo-example](https://github.com/scullxbones/akka-persistence-mongo-example/)?  I may have missed something in creating the example.

**Comment by dmassart** [comment]
Hi Brian @scullxbones ,

Thanks for this.  I just realized that I was using an unsupported version of  mongodb.  Cloning the example and running it against mongodb 3.4.1 reproduces the problem.  Downgrading to mongodb 3.2.11, deleting the db and running the example again fixes the problem.

Best,

David

**Comment by scullxbones** [comment]
Ah!  Yes.  Hopefully `3.4` will just be a driver upgrade to support, it's tracked by #135
