### ISSUE TITLE
Write directly to journal, bypassing actor lifecycle.

### ISSUE THREAD

**Issue by jCalamari** [scullxbones/akka-persistence-mongo#146]
Is it possible to write directly to Mongo journal? If so, could you provide an example, please?

**Comment by scullxbones** [comment]
Hi @jCalamari 

No, not at this point.  Or at least not in an officially supported way.

I think this request might be solved by #42?

**Comment by scullxbones** [comment]
Just as a footnote, found the following project while researching something else - may be of use?

https://github.com/dnvriend/akka-persistence-jounal-writer
