### ISSUE TITLE
Akka 2.5 support

### ISSUE THREAD

**Issue by thjaeckle** [scullxbones/akka-persistence-mongo#148]
Hi.

I just wondered what it would take to take akka-persistence-mongo to Akka 2.5 and tried it out.
As far as I can see only minor adjustments in akka-persistence-query need to be made:
- renaming dependency from "akka-persistence-query-experimental" to "akka-persistence-query"
- using new `Offset` type used in `EventEnvelope` instead of `long` in `Event.toEnvelope()`
- instead of importing `AllPersistenceIdsQuery`, import `PersistenceIdsQuery` and overridden `allPersistenceIds` methods to `persistenceIds` (and rename some own types also from "AllPersistenceIds..." to "PersistenceIds...")

With almost no sbt and scala knowledge I managed to get a very basic example working with Akka 2.5. 👍 

Are you interested in a pull request?
That would probably be a version 2.0.0-SNAPSHOT, wouldn't it?

Regards Thomas

**Comment by scullxbones** [comment]
Hi @thjaeckle 

Sure that would be great.  I *think* it would be the 2.x series based on how the plugin has been versioned before.  Then again there is something to be said for making it the `2.5` series to match up with akka version.  Need to think about that, but don't let that slow you down on a PR.

Thanks!

**Comment by scullxbones** [comment]
Fixed in release `2.0.0`, thanks @thjaeckle !
