### ISSUE TITLE
Add Support for Mongo 3.4 in 1.x series

### ISSUE THREAD

**Issue by ulrichwinter** [scullxbones/akka-persistence-mongo#162]
currently the 1.x version of akka-persistence-mongo (compatible with akka 2.4) supports Mongo versions 2.6, 3.0, 3.2.
Please add support for Mongo 3.4.
Upgrading to akka 2.5 is not practical for projects using the 1.x Version of the persistence plugin.

I've already seen issue #135, but I'm not sure if that ticket is targeted for the 1.x/akka2.4 Version.

**Comment by scullxbones** [comment]
Hi @ulrichwinter 

The plugin may work against `3.4` already, depending on the driver version used (e.g. I think Casbah `3.1` supports it).  #135 is more about what versions the continuous test suite runs against.  It's more of a "certified against" than anything else.

That said, I think it's fine to backport #135 to the `1.x` branch, no problem.  I'll make a note in that ticket and close this one.
