### ISSUE TITLE
java.lang.NoClassDefFoundError: reactivemongo/akkastream/package$

### ISSUE THREAD

**Issue by nmolenaar** [scullxbones/akka-persistence-mongo#166]
Hey guys I'am getting the stranges error while settingup the project with the package from this repo.

My build.sbt

libraryDependencies ++= {
  val akkaV = "2.5.4"
  val akkaHttpV = "10.0.10"
  val reactiveMongoV = "0.12.6"
  Seq(
    "com.typesafe.akka" % "akka-slf4j_2.11" % akkaV,
    "org.slf4j" % "slf4j-simple" % "1.7.25",
    "com.typesafe.akka" %% "akka-actor" % akkaV,
    "com.typesafe.akka" %% "akka-stream" % akkaV,
    "com.typesafe.akka" %% "akka-http" % akkaHttpV,
    "com.typesafe.akka" %% "akka-slf4j" % akkaV,
    "com.typesafe.akka" %% "akka-persistence" % akkaV,
    "com.github.scullxbones" %% "akka-persistence-mongo-rxmongo" % "2.0.3",
    "org.reactivemongo" %% "reactivemongo" % reactiveMongoV
  )
}

and here is my error: 

`project_name[ERROR] java.lang.NoClassDefFoundError: reactivemongo/akkastream/package$
project_name[ERROR] 	at akka.contrib.persistence.mongodb.RxMongoJournaller$$anonfun$maxSequenceNr$1.apply(RxMongoJournaller.scala:197)
project_name[ERROR] 	at akka.contrib.persistence.mongodb.RxMongoJournaller$$anonfun$maxSequenceNr$1.apply(RxMongoJournaller.scala:201)
project_name[ERROR] 	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
project_name[ERROR] 	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
project_name[ERROR] 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
project_name[ERROR] 	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
project_name[ERROR] 	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
project_name[ERROR] 	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
project_name[ERROR] 	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
project_name[ERROR] 	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
project_name[ERROR] 	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
project_name[ERROR] 	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
project_name[ERROR] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
project_name[ERROR] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
project_name[ERROR] 	at java.lang.Thread.run(Thread.java:745)
project_name[ERROR] Caused by: java.lang.ClassNotFoundException: reactivemongo.akkastream.package$
project_name[ERROR] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
project_name[ERROR] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
project_name[ERROR] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
project_name[ERROR] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
project_name[ERROR] 	... 15 more`

Any idea what is going on? I've read the Readme a couple of times already.

**Comment by scullxbones** [comment]
@NicholasMolenaar - i'm seeing on `reactivemongo.org` that there's a new dependency, I think this was included before:

```
libraryDependencies += "org.reactivemongo" %% "reactivemongo-akkastream" % "0.12.6"
```

Can you confirm if adding this dependency fixes the issue for you?  If so, I can update the docs.

Thanks!

**Comment by scullxbones** [comment]
My mistake, I added this dependency but didn't document it.  Documentation is fixed now.  

Thanks for the report!
