### ISSUE TITLE
In Akka 2.5.x, there are actually two circuit breakers, put that in the docs or rely on the Akka circuit breaker only

### ISSUE THREAD

**Issue by fabiangebert** [scullxbones/akka-persistence-mongo#168]
After long tedious hours of debugging, I became aware of the fact that AsyncWriteJournal from akka-persistence already has a circuit breaker logic in place that will be enforced no matter if you turn on the circuit breaker in akka-persistence-mongo or not. As far as I can see, other plugins (e. g. dynamodb) don't have another circuit breaker. Why do we need it here?
I have the following alternative suggestions:
* make sure to document how to configure the two circuit breakers
* do not use another circuit breaker in the MongoDB plugin

Correct me if I'm wrong in my analysis and thanks for the otherwise great plugin!

**Comment by scullxbones** [comment]
Ah, interesting.  This plugin has had a circuit breaker since very early on, akka 2.3 timeframe.  There's no need to have a redundant one, this ticket can track the removal of ours.

**Comment by scullxbones** [comment]
Ended up removing this plugin's circuit breaker entirely.  

This should be fixed in the 2.0.4 release.

Thanks for the report!
