### ISSUE TITLE
Sharded persistent actors send huge amount of 'createIndexes' commands to MongoDB

### ISSUE THREAD

**Issue by yfcai** [scullxbones/akka-persistence-mongo#169]
When using persistent actors with cluster sharding and Casbah driver, a huge amount of `createIndexes` commands are sent to MongoDB. The amount of `createIndexes` correlates with the number of `persist` calls. The commands slow down MongoDB due to lock acquisition, which takes anywhere between 1 to 100 milliseconds.

Reproducer:
https://github.com/yfcai/reproducer-createIndexes

According to the debugger, the branch `driver.useSuffixedCollectionNames == true` in [CasbahPersistenceJournaller:63](https://github.com/scullxbones/akka-persistence-mongo/blob/c4ca0048dd900166f95b1fe2bce74c1e73ae0007/casbah/src/main/scala/akka/contrib/persistence/mongodb/CasbahPersistenceJournaller.scala#L63) is always taken, despite the config keys `akka.contrib.persistence.mongodb.mongo.suffix-builder.{separator, class}` not being set.

**Comment by scullxbones** [comment]
Ended up fixing the code path that caused the `createIndex` calls such that if suffix collections are not used, these are only called once.

This should be fixed in `2.0.4`.

Thanks for the report!

**Comment by yufei-cai** [comment]
Thanks for the quick fix, verified with v2.0.4 that excessive createIndexes commands are no longer sent.
