### ISSUE TITLE
Exception in MongoPersistenceExtension.createExtension

### ISSUE THREAD

**Issue by michaelom** [scullxbones/akka-persistence-mongo#17]
`MongoPersistenceExtension` invokes `ConfigFactory.load())` which causes an `ConfigException$UnresolvedSubstitution` to be thrown if there are unresolved substitutions (e.g. ${com.my.key}).

When creating an actor system we resolving missing substitutions with a another configuration.

```
Config resolvedConfig = akkaConfig.resolveWith(springConfig);
ActorSystem.create(actorSystemName(), resolvedConfig);
```

This is a rare use case and for most applications not an issue, but the Extension should not assume that ConfigFactory.load() has all values resolved. Why not just take the backing config of the ExtendedActorSystem

**Comment by scullxbones** [comment]
I think the intent was to fail fast on missing configuration.  I can maybe get away with the ExtendedActorSystem's config, will take a look.

**Comment by scullxbones** [comment]
@michaelom ... so I think it was a failed attempt at providing user overrides for configuration.  There was no way to actually set the override.  I've just removed it and simplified the code.  

Please give 0.2.2 a whirl and report back if there are more issues.

Thanks for the report!

**Comment by michaelom** [comment]
@scullxbones 
Works!

So far no issues with 0.2.2. I keep you posted.

Nice DriverSpec btw.
