### ISSUE TITLE
ERROR akka.actor.ActorInitializationException: exception during creation in versions 1.4 and 2.0

### ISSUE THREAD

**Issue by qstyler** [scullxbones/akka-persistence-mongo#175]
Hi everyone!
I'm trying to use this library (rxmongo version) with my projct, but I ran into a problem.
Here's what happens:
I'm adding this dependency to my `build.sbt`:
`"com.github.scullxbones" %% "akka-persistence-mongo-rxmongo" % "2.0.4"`
Then I configure my akka as follows:
```
persistence {
  journal.plugin = "akka-contrib-mongodb-persistence-journal"
  snapshot-store.plugin = "akka-contrib-mongodb-persistence-snapshot"
}

contrib {
  persistence.mongodb {
    mongo {
      mongouri = "mongodb://localhost:27017/akka-persistence-example"
      journal-collection = "journal"
      journal-index = "journal_index"
      snaps-collection = "snapshots"
      snaps-index = "snaps_index"
      journal-write-concern = "Acknowledged"
    }
  }
}
```

But when I run my program, I get this error message:
`[ERROR] [10/28/2017 14:38:07.504] [Test-akka.actor.default-dispatcher-3] [akka://Test/system/akka-contrib-mongodb-persistence-snapshot] null
akka.actor.ActorInitializationException: akka://Test/system/akka-contrib-mongodb-persistence-snapshot: exception during creation`

I cloned this project to check what was going on
`https://github.com/scullxbones/akka-persistence-mongo-example`

It has rxmongo version 1.3.7 as the dependency:
`libraryDependencies += "com.github.scullxbones" % "akka-persistence-mongo-rxmongo_2.11" % "1.3.7"`

This project was compiling and running. Then I tried to change some versions and found out that the error I mentioned above appears whenever I use the version "1.4.*" or higher including "2.0".

So the question is: is it a bug? Is it just me misconfiguring this library?

Some more lines from my build.sbt:
```
scalaVersion := "2.12.3"
val akkaVersion = "2.5.4"
```

But this happens for me with any combination of 2.4 and 2.11.

**Comment by scullxbones** [comment]
Hi @qstyler  

Can you confirm which `rxmongo` dependency version you're using?  You may need to use a `0.12.x` series of `rxmongo` due to compatibility issues between `0.11.x` and `0.12.x`.

Also check out #166 - another dependency may be needed, again - depending on the `rxmongo` version used.

**Comment by scullxbones** [comment]
It looks like another minor version of rxmongo (@ `0.12.2`+) has a backward incompatibility, I was able to get the latest `1.x` series working on the test project with the following changes to the build.sbt:

```diff
diff --git a/build.sbt b/build.sbt
index 8e4a460..66f7ef7 100644
--- a/build.sbt
+++ b/build.sbt
@@ -14,7 +14,8 @@ libraryDependencies += "com.typesafe.akka" % "akka-persistence_2.11" % akkaVersi
 //libraryDependencies += "org.iq80.leveldb"            % "leveldb"          % "0.7"
 //libraryDependencies += "org.fusesource.leveldbjni"   % "leveldbjni-all"   % "1.8"
 // In MongoDB using the reactive mongo driver
-libraryDependencies += "com.github.scullxbones" % "akka-persistence-mongo-rxmongo_2.11" % "1.3.7"
+libraryDependencies += "com.github.scullxbones" % "akka-persistence-mongo-rxmongo_2.11" % "1.4.3"
 
 // reactive mongo
-libraryDependencies += "org.reactivemongo" % "play2-reactivemongo_2.11" % "0.11.14"
+libraryDependencies += "org.reactivemongo" % "play2-reactivemongo_2.11" % "0.12.1-play24"
+libraryDependencies += "org.reactivemongo" %% "reactivemongo-akkastream" % "0.12.1"
```

I never did see an `ActorInitializationException` though.

**Comment by qstyler** [comment]
Thank you!
I was missing `"play2-reactivemongo"` dependency.
Your docs [here](https://github.com/scullxbones/akka-persistence-mongo/blob/master/docs/akka25.md) mention only `"reactivemongo-akkastream"` and that's why I got confused.
