### ISSUE TITLE
Persistence failure when replaying events for persistenceId. Database doesn't exist.

### ISSUE THREAD

**Issue by qstyler** [scullxbones/akka-persistence-mongo#176]
Hi again!

So I found out another issue with your (probably RX mongo) library. And its different versions.
Taking your [Example project](https://github.com/scullxbones/akka-persistence-mongo-example) with version `"1.3.7"` as example I expected version `"2.0.4"` to create database and collections automatically.

But instead of that it fails with an error when I run the code.
```
[ERROR] [10/30/2017 17:33:17.466] [persistent-actors-akka.actor.default-dispatcher-2] [akka://persistent-actors/user/counter] Persistence failure when replaying events for persistenceId [counter]. Last known sequence number [0] (reactivemongo.api.commands.bson.DefaultBSONCommandError: CommandError[code=26, errmsg=Database akka-persistence-example doesn't exist, doc: {
  "ok": NumberDecimal(0.0),
  "errmsg": "Database akka-persistence-example doesn't exist",
  "code": 26,
  "codeName": "NamespaceNotFound"
}])
```

It wouldn't automatically create a collection if I database exists and empty with a similar error message.

Am I missing some tricky config value? Or is it really a bug?

These are my dependencies:
```
// Akka Persistence
libraryDependencies += "com.typesafe.akka" %% "akka-persistence" % akkaVersion
libraryDependencies += "com.github.scullxbones" %% "akka-persistence-mongo-rxmongo" % "2.0.4"
libraryDependencies += "org.reactivemongo" %% "reactivemongo-akkastream" % "0.12.7"

// reactive mongo
libraryDependencies += "org.reactivemongo" %% "play2-reactivemongo" % "0.12.7-play26"
```

Akka version is "2.5.4".

**Comment by scullxbones** [comment]
Hi @qstyler,

There's never been a configuration item in the plugin to create the database, if it happens, that's been up to the drivers.  In my experience, the database is created as an operations task outside of running the application.

Can you try to duplicate with the rxmongo driver `0.12.1` instead of `0.12.7` like I mentioned in #175 ?

**Comment by qstyler** [comment]
Ok thanks for a hint.

A little investigation:

Version "0.12.1" creates a database, but gives another error.
```
[ERROR] [SECURITY][10/31/2017 07:02:15.918] [persistent-actors-akka.actor.default-dispatcher-3] [akka.actor.ActorSystemImpl(persistent-actors)] Uncaught error from thread [persistent-actors-akka.actor.default-dispatcher-3]: akka.actor.ActorSystem.isTerminated()Z, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[persistent-actors]
java.lang.NoSuchMethodError: akka.actor.ActorSystem.isTerminated()Z
	at reactivemongo.api.MongoDriver.close(api.scala:916)
```

Version "0.12.2" and "0.12.3" both create a database, but flushes a lot of errors when program terminates.

Version "0.12.4", "0.12.5" and "0.12.6" work just fine.

Thanks again!

**Comment by GoranSchumacher** [comment]
Testing akka persistence with;
      "com.typesafe.akka" %% "akka-persistence" % "2.5.4",
      "com.github.scullxbones" %% "akka-persistence-mongo-rxmongo" % "2.0.4",
      "org.reactivemongo" %% "reactivemongo-akkastream" % "0.12.7",
      "org.reactivemongo" %% "reactivemongo" % "0.12.7",

Get's;
[ERROR] [11/12/2017 09:58:15.835] [ShardingSystem-akka.actor.default-dispatcher-33] [akka.tcp://ShardingSystem@127.0.0.1:2551/system/sharding/ExamplePersistentActor/37/37] Persistence failure when replaying events for persistenceId [37]. Last known sequence number [0] (reactivemongo.api.commands.bson.DefaultBSONCommandError: CommandError[code=26, errmsg=no database, doc: {
  "ok": NumberDecimal(0.0),
  "errmsg": "no database",
  "code": 26
}])

When using;
      "org.reactivemongo" %% "reactivemongo" % "0.12.6",

It creates the database and collections fine.
After this you can use 0.12.7.
