### ISSUE TITLE
rxmongo: Replay journal with max replay events > Max.IntValue

### ISSUE THREAD

**Issue by marcuslinke** [scullxbones/akka-persistence-mongo#18]
When setting ```override val autoUpdateReplayMax = Long.MaxValue```  in a persistent view actor only 101 events are replayed per ```Update```. This is due to conversion the ```Long``` value to an ```Int``` via ```max.toInt``` here:

https://github.com/scullxbones/akka-persistence-mongo/blob/master/rxmongo/src/main/scala/akka/contrib/persistence/mongodb/RxMongoPersistenceJournaller.scala#L118

If ```max``` is greater then ```Int.MaxValue``` it results in a negative value so rxmongo will use its default of 101 which is a problem when processing mass of events.

**Comment by marcuslinke** [comment]
Here is a PR: https://github.com/scullxbones/akka-persistence-mongo/pull/19

**Comment by scullxbones** [comment]
Fixed by PR #19
