### ISSUE TITLE
Support selection of reservoir for timers and histograms in metrics

### ISSUE THREAD

**Issue by Yannic92** [scullxbones/akka-persistence-mongo#193]
Hi,
I've the following problem:
I want to store the mongodb metrics in Kamons metric instruments. 
Therefore I've created a ScheduledReporter that takes the metric values from Dropwizards Metrics and stores them in Kamons metric instruments.

So far so good, but the values are still contained in Dropwizards Metrics.
There is a reservoir that would help me with that: The [HdrHistogramResetOnSnapshotReservoir][1].

It would be nice to define this reservoir to be used for timers and histograms.
Unfortunately [currently][2] there are just the default reservoirs used.
Dropwizard allows to pass a second argument additionally to the name that is a supplier of the metric (timer/histogram). 
Using this supplier would make it possible to create the timer with the specified reservoir.

How do you think about this?

[1]:https://bitbucket.org/marshallpierce/hdrhistogram-metrics-reservoir
[2]:https://github.com/scullxbones/akka-persistence-mongo/blob/3fede4992d3dc193dd62136ed61a141bfb157ece/common/src/main/scala/akka/contrib/persistence/mongodb/MongoJournal.scala#L164:L171

**Comment by scullxbones** [comment]
Hi @Yannic92 - sorry I thought I had replied to this already.

Sure I think that would be good, I will happily review a PR on this.

**Comment by gbrd** [comment]
would it be possible to avoid needing dropwizard metrics dependency when using another metricBuilder implementation ?

**Comment by thjaeckle** [comment]
@gbrd yes, absolutely - that's how we (the Ditto project from which the PR originated) will use it

**Comment by gbrd** [comment]
I try to  .exclude("nl.grons", "metrics-scala_2.12"), but it does not work. 
I may try to exclude only java lib.

**Comment by Yannic92** [comment]
@gbrd With 2.2.2 it should be possible to exclude dropwizard

**Comment by gbrd** [comment]
thanks ! I will try
