### ISSUE TITLE
journal index size

### ISSUE THREAD

**Issue by marcuslinke** [scullxbones/akka-persistence-mongo#20]
Having stored 200 million events in the journal the unique index is above 150GByte in size. Maybe this could be optimized somehow maybe by splitting the journal into multiple collections? WDYT?

**Comment by scullxbones** [comment]
Wow that's a big index.  Do you have many processors and less events?  Or fewer processors and many events?

If you have many (or at least more than a couple) processors, I can imagine using [mongo sharding](http://docs.mongodb.org/manual/tutorial/shard-collection-with-a-hashed-shard-key/) on the journal would allow you to split it into parts, sharding on the processor id.  This would allow horizontal write scaling.  At a journal that size, i'd expect you are starting to see slowdown in write performance.  If you end up going that way, let me know, it would be good to note in the README that it has been done.

Can you run the [stats](http://docs.mongodb.org/manual/reference/method/db.collection.stats/#db.collection.stats) command for the journal collection and paste the results in a comment on this issue? It would be good to get a better understanding of what's going on.  You can run it with a scale of `1024` for easier reading.

**Comment by marcuslinke** [comment]
I'm working on a project in the statistics domain therefore I have only one processor. So sharding will be no option i think. There are 200 million events in the journal (updated my original comment) and here is the output of ```db.journal.stats()```:

```
{
	"ns" : "eventstore.journal",
	"count" : 200368640,
	"size" : 92971048960,
	"avgObjSize" : 464,
	"storageSize" : 97308921184,
	"numExtents" : 66,
	"nindexes" : 2,
	"lastExtentSize" : 2146426864,
	"paddingFactor" : 1,
	"systemFlags" : 1,
	"userFlags" : 0,
	"totalIndexSize" : 15129164736,
	"indexSizes" : {
		"_id_" : 6501154576,
		"journal_index" : 8628010160
	},
	"ok" : 1
}
```

**Comment by scullxbones** [comment]
Looking at that dump, it looks like the total index size is 15GB.  Still huge of course.  For reasonable performance in mongo, the index needs to fit in RAM, so I have to imagine you're fairly close to an extreme slowdown in read performance.

Do you need all of that history of 200MM events for a single processor?  What is your snapshot strategy currently?

**Comment by marcuslinke** [comment]
Seems i was a bit dizzy yesterday. Sure this is 15GB "only". Thanks for pointing this out and sorry for confusion. I've 8GB RAM here only but replay performance is reasonable nevertheless. 

I think my use case is somewhat unusual. As I said its in the statistics domain and the main idea is to store all statistic relevant events (page impressions of a website) in the journal to be able to construct different view models later by replaying the events. So at the processor side there is no domain model or state to snapshot and at the view side snapshotting is not possible due to the size of the (view) models.

The idea comes from my experiments with CQRS (axonframework.org) in another project and my interest in evaluating akka-persistence for it.  But maybe I've underestimated the handling of massive events...

**Comment by scullxbones** [comment]
So with the assumption that your statistics are per `web page`, have you thought about a processor-per-page (or maybe even some categorization of page) model?  I think even if you left Mongo for something that scales better, like either of Martin's Kafka or Cassandra journals, it's tough for a single processor to shard the collection into pieces.

You could do some kind of sharding by sequence number, but it would probably take a significant hit on replay due to the need to query > 1 of the shard servers for data.  At least writes would be fast.  I guess the good news is you can test this without making code changes and see if it works for you.

**Comment by marcuslinke** [comment]
@scullxbones Thanks for your input. I've to rethink the whole architecture i guess. My main problem at the moment is the read model that is persisted into mongo also. As for fast reading it needs some indexes but it seems the more indices exist the more it slows down insert performance dramatically.

However, i don't want to bother you so closing this issue now. Thanks!

**Comment by scullxbones** [comment]
@marcuslinke no problem, happy to help out.  Thanks for the interesting problem to think about!
