### ISSUE TITLE
UnsupportedOperationException thrown by RxMongo CurrentEventsByTag

### ISSUE THREAD

**Issue by jeremystone** [scullxbones/akka-persistence-mongo#200]
Get:
>java.lang.UnsupportedOperationException: empty.reduceLeft
	at scala.collection.LinearSeqOptimized.reduceLeft(LinearSeqOptimized.scala:135)
	at scala.collection.LinearSeqOptimized.reduceLeft$(LinearSeqOptimized.scala:134)
	at scala.collection.immutable.List.reduceLeft(List.scala:86)
	at akka.contrib.persistence.mongodb.CurrentEventsByTag$.$anonfun$source$30(RxMongoReadJournaller.scala:126)
	at akka.stream.impl.fusing.Map$$anon$9.onPush(Ops.scala:51)
...

Looks like this was introduced by #196 (see 0bce3c57ba24aaa1ec69f7b3df1437a2c14d0a97) in the case where a new application starts up and no journal collections have been created at the time the CurrentEventsByTag query is issued.

Replacing the reduceLeft code with something like:
```
Source(xs.map(c =>
              c.find(query)
               .sort(BSONDocument(ID -> 1))
               .cursor[BSONDocument]()
               .documentSource()
            )).flatMapConcat(identity)
```
may fix it. 

(There are two other instances where reduceLeft is used to concat query sources from multiple collections in RxMongoReadJournaller.scala).

Can look at creating a PR if you like.

**Comment by scullxbones** [comment]
Damn.  Good catch.  Would definitely appreciate a PR.  If not, I may be able to get to it this weekend.

**Comment by jeremystone** [comment]
Happy to do that but unlikely to get chance to look at it before next week (as it's close to 5pm here in UK).

**Comment by jeremystone** [comment]
Splendid! Thank you.
