### ISSUE TITLE
Passing DB objects directly into journal collection with new ScalaDriver is broken

### ISSUE THREAD

**Issue by thjaeckle** [scullxbones/akka-persistence-mongo#215]
Hi there.

I just tried updating from the Casbah driver to the Scala driver.
We make use of the "Passing DB objects directly into journal collection" feature - so previously in Casbah we used `com.mongodb.DBObject` to directly persist JSON structures into MongoDB.

With the new Scala driver the mechanism works as expected from MongoDB back to the application code (e.g. for already existing journal entries): in that case we get a `org.bson.BsonDocument` offered.

The docs state that following class should be used for Scala driver:
> `org.scala.bson.BsonDocument` (using native scala driver)

Using `org.scala.bson.BsonDocument.apply()` creates an instance of `org.bson.BsonDocument` which we used in order to put into `persist()`.
But that leads to following event fields: `_t=ser` and `_h=org.bson.BsonDocument`, so not as expected `_t=bson`.

It however does work as expected when wrapping the `org.bson.BsonDocument` into a `org.mongodb.scala.bson.collection.immutable.Document` in the `persist()` method.

I guess that was not intended, or was it?

I think that the `ScalaDriverSerializers` would have to work with another `DocumentType[D]` - and that instead of `org.mongodb.scala.bson.collection.immutable.Document`, `org.bson.BsonValue` would be the right candidate for the DocumentType.

Why `BsonValue` instead of `BsonDocument`?
With the Casbah driver it was possible to also persist a `com.mongodb.BasicDBList` (which is a subtype of `com.mongodb.DBObject`) directly as "bson" type into the DB.
With the `org.bson.BsonDocument` that won't work any longer - as `BsonArray` is not a subtype of `BsonDocument`.

What do you think about that?
I could try providing a PR if you would approve such changes.

**Comment by scullxbones** [comment]
Hi @thjaeckle -

> I guess that was not intended, or was it?

No that's not intended.

> Why BsonValue instead of BsonDocument?

That was an oversight on my part.  `BsonValue` is more flexible and thus a better choice.

I certainly would be happy to review a PR changing the document type to `org.bson.BsonValue` for the native scala driver.

Thank you!

**Comment by scullxbones** [comment]
Released with `v2.2.2`
