### ISSUE TITLE
Question regarding deserialization when switching to SerializerWithStringManifest

### ISSUE THREAD

**Issue by orElse** [scullxbones/akka-persistence-mongo#220]
Hi,

We are using protobuf for serialization and currently try to switch to SerializerWithStringManifest to get rid of some legacy classes

from reading the akka docu (https://doc.akka.io/docs/akka/2.5.21/serialization.html?language=scala#serializer-with-string-manifest) this seemed like to be manageable since we included the manifest when serializing

> If the data was originally serialized with Serializer and in a later version of the system you change to SerializerWithStringManifest the manifest string will be the full class name if you used includeManifest=true, otherwise it will be the empty string.

My old event payload currently looks something like this:

```
            "v" : 1,
            "pid" : "/user/sharding/..../....",
            "sn" : { "$numberLong": "3" },
            "_tg" : [ ],
            "_t" : "ser",
            "p" : { "$type":0, "$binary":"....."},
            "_h" : "x.x.x.Class",
            "_sm" : null,
            "_si" : 40001000,
            "_w" : "a3be4dd1-24a7-4812-bb29-5f30b94bd88f"
```

But after updating the serializer, removing the class and the serialization binding I have the issue that deserialization fails since the manifest passed into the serializer is empty.

When looking into akka.contrib.persistence.mongodb.Serialized I think during deserialization I land in 

```
// No manifest id serialized, class doesn't exist - use write-time configuration
      case (None, Some(id),Failure(_)) =>
        ser.deserialize[X forSome { type X <: AnyRef }](bytes, id, clazz.toOption)
```

Would it be possible to have an option (e.g. by config) to use 
    ser.deserialize(bytes, clazzSer.identifier, className)
instead? 

Kind regards

**Comment by scullxbones** [comment]
Hi @orElse -

It looks like your manifest is in fact empty: `"_sm": null`

Is there a way to land in this block?

```scala
      // No manifest id serialized, prefer read-time configuration
      case (None, _, Success(clazzSer)) =>
        ser.deserialize[X forSome { type X <: AnyRef }](bytes, clazzSer.identifier, clazz.toOption)
```

For that you'd need `ser.serializerFor(c)` to yield the expected serializer for your obfuscated class name `"_h" : "x.x.x.Class"`.  Is it possible to supply that configuration?

**Comment by orElse** [comment]
Hi,

thanks for your reply and also the great plugin

ideally I would have liked to remove the old class completely since it was generalized and moved - so I wouldn't any longer get a serializer for it. Also the old class was written with a Serializer without string manifest, but still with include manifest enabled. For the new class I kept the serializer id and followed the instructions regarding the SerializerWithStringManifest from the akka documentation.

As a workaround I have currently kept the old classes and deprecated them, but deserialize them to my new ones.

So probably my only other chance to make this work, would be to do a mongodb update and write the string manifest info based on the class name (I just have to make sure that for the affected pids I have no events which were written with the old legacy format of the plugin, otherwise I would have to migrate them)

**Comment by scullxbones** [comment]
> ideally I would have liked to remove the old class completely since it was generalized and moved

Ah ok I missed that first time around even though you explicitly said it "to get rid of some legacy classes".

Given that you're probably landing in this block:

```scala
// No manifest id serialized, class doesn't exist - use write-time configuration
      case (None, Some(id),Failure(_)) =>
        ser.deserialize[X forSome { type X <: AnyRef }](bytes, id, clazz.toOption)
```

I assume that you can't re-use the old `serializerId = 40001000` to point to a serializer that can deserialize both old and new types?

Using this path from akka-serialization:

```scala
  /**
   * Deserializes the given array of bytes using the specified serializer id,
   * using the optional type hint to the Serializer.
   * Returns either the resulting object or an Exception if one was thrown.
   */
  def deserialize[T](bytes: Array[Byte], serializerId: Int, clazz: Option[Class[_ <: T]]): Try[T] =
    Try {
      val serializer = try getSerializerById(serializerId) catch {
        case _: NoSuchElementException ⇒ throw new NotSerializableException(
          s"Cannot find serializer with id [$serializerId]. The most probable reason is that the configuration entry " +
            "akka.actor.serializers is not in synch between the two systems.")
      }
      serializer.fromBinary(bytes, clazz).asInstanceOf[T]
    }
```

I'm assuming it's impossible or at least unreasonable (e.g. you'd have to write some kind of deep inspection because many event classes share the same serializerId) to write the legacy class replacement deserializer code in a way that has a `None` manifest passed:

```
  /**
   * Produces an object from an array of bytes, with an optional type-hint;
   * the class should be loaded using ActorSystem.dynamicAccess.
   */
  @throws(classOf[NotSerializableException])
  def fromBinary(bytes: Array[Byte], manifest: Option[Class[_]]): AnyRef
```

If one assumes the journal is immutable, one solution could be some kind of translation in code of the type hint "_m" to allow the akka serialization logic to use a different serializer, despite no string manifest being supplied.

If the journal is not considered immutable (or at least the meta data isn't) - I think your described approach of updating mongo is a good one.  That's probably the simplest approach.

**Comment by scullxbones** [comment]
Or could do a 2 phase expand contract approach. Something like the following:

Phase 1
- add new event classes, serializer with string manifest, leave old event classes plus old serializer
- inject an event adapter to up cast deserialized old events to new events
- deploy to production and stabilize
- once stable, apply db script discussed above

Phase 2
- delete old event classes, remove event adapter
- deploy

Maybe this was your plan already. The good news is you chose protobuf which makes this possible, even if tedious.

**Comment by orElse** [comment]
Thanks for the hints. I will check them with my team and also have another look into the akka serializers  and the serializers extension. 
Since the 2 types are treated a little differently internally in the serializers extension from what I have seen and currently Afaik there is no way to find out which type is behind a serializer id, this doesn't make it easier. 
For the time being I can keep the old classes in a first step and have to find a sustainable solution once we decide to switch generally to serializers with string Manifest, so that we don't run into this again when somebody removes a legacy class

**Comment by scullxbones** [comment]
I think this issue has reached its resolution, please let me know if otherwise.
