### ISSUE TITLE
Change `provided` dependencies to `compile` dependencies

### ISSUE THREAD

**Issue by Woodz** [scullxbones/akka-persistence-mongo#226]
Firstly, thank you for providing such a useful library! I found it very easy to use once I got setup, but I feel that using `provided` scope for dependencies makes the setup process harder than it should be. In order to get the library working, I had to examine https://github.com/scullxbones/akka-persistence-mongo/blob/063e1b8e594792358161afb765f76cc14201205d/build.sbt#L97 to find the expected Mongo Scala version.

There is a question on whether JARs should have provided dependencies at https://stackoverflow.com/questions/40789902/should-jars-have-provided-dependencies which has a nice comment "As a library writer, you don't really know how your library is going to be used". Therefore, I feel it would benefit the library to change `provided` driver dependencies to `compile` scope

**Comment by scullxbones** [comment]
Thanks - let me do some research on the subject.  I know that I specifically chose `provided` early on, but I'm not immediately remembering why.

**Comment by scullxbones** [comment]
Fixed with `2.2.5` - thanks for the report!
