### ISSUE TITLE
Version 2.2.5 for scala 2.12 not available in maven central

### ISSUE THREAD

**Issue by janessbach** [scullxbones/akka-persistence-mongo#231]

**Comment by scullxbones** [comment]
Yep looks like cross-build got hosed with the sbt 1.x ugprade.  Thanks for the report!

**Comment by scullxbones** [comment]
Fixed now.  `search.maven.org` is lagging behind, but typing in the direct url in the address bar shows the correct information (replace `2.2.4` with `2.2.5` on a _2.12 jar).

Again, thanks for letting me know!
