### ISSUE TITLE
upgrade to casbah_2.10 version 2.8.1

### ISSUE THREAD

**Issue by ulrichwinter** [scullxbones/akka-persistence-mongo#26]
We need to upgrade to mongo-java-driver version 2.13.x in order to use a MongoDB V3.0 and this is the minimum mongo-java-driver which is documented as compatible
http://docs.mongodb.org/ecosystem/drivers/driver-compatibility-reference/#reference-compatibility-mongodb-java

Currently akka-persistence-mongo depends on casbah_2.10 version 2.7.4.
casbah itself upgraded to mongo-java-driver 2.13.1 as of version 2.8.1
http://mongodb.github.io/casbah/changelog.html

So because we use akka-persistence-mongo I request to upgrade it to the current casbah-version
casbah_2.10 - version: 2.8.1

**Comment by michaelom** [comment]
+1 for driver support for MongoDB 3.0

**Comment by scullxbones** [comment]
Hi, sorry meant to reply yesterday.

The driver dependencies are marked provided with the intention that users have some leeway on the exact version used.

So if the driver is backward compatible, you should be able to use it directly without a library change. 

Also note, I've never tested on Mongo 3.0.  I think I note the versions tested on the README.  Let me know what issues you run into, assuming you can simply use the driver version you need.

**Comment by ulrichwinter** [comment]
Hi, 

that's right - so ticket may be closed, because change is not really necessary.

Nevertheless, wouldn't it be desireable to upgrade to the current version of the casbah driver during the build and especially the test process?
I suggest even running the test kit against both: a Mongo 2.6 and a Mongo. 3.0

**Comment by scullxbones** [comment]
Yep agreed, I'd definitely want the tests to pass for Mongo 3.0 before saying it was supported.  Let me know if you run into any major issues.  I'm going to wait on at Reactive Mongo 0.11 (currently a snapshot) to release and try to get running on that.  This way both drivers will support 3.0.

**Comment by sourcekick** [comment]
+1

**Comment by scullxbones** [comment]
Fixed with 0.4.0

**Comment by michaelom** [comment]
+1
