### ISSUE TITLE
Support URI style connections to MongoDB

### ISSUE THREAD

**Issue by sourcekick** [scullxbones/akka-persistence-mongo#28]
As @ulrichwinter pointet out in #27 it would be great if the plugin would support URI stype connections to MongoDB, at least through casbah.

The best thing is: using a URI, configuration of the authentication method and other options is easy and does not require any additonal glue code.

In my project setting it would actually be very helpful to get this feature within the next two weeks or so, i.e. without waiting for reactivemongo to follow-up with a new release, since we are using MongoDB 3.0, your plugin, and our schedule is extremely tight towards upcoming production.

casbah supports URI style connectiosn since version 2.0, so you would not have to compile against a newer casbah version to introduce this feature.

**Comment by sourcekick** [comment]
Links:

URI style connections to MongoDB support new options without further glue code
http://mongodb.github.io/casbah/guide/connecting.html#id2

casbah supports MongoClientURI since 2.0
https://github.com/mongodb/casbah/blob/master/casbah-core/src/main/scala/MongoClientURI.scala

**Comment by sourcekick** [comment]
Solving this issue would also solve #27 for people who use the current plugin at their own risk with a newer 2.8.x casbah driver to connect to MongoDB 3.0 and utilize new available options via the URI connection string.

**Comment by scullxbones** [comment]
Fixed with 0.4.0
