### ISSUE TITLE
EventsByTagQuery is always restarting

### ISSUE THREAD

**Issue by gael-ft** [scullxbones/akka-persistence-mongo#321]
Hello,

I started using this plugin recently.
Note I am running a local mongod and everything seems to work well for writing persistent events.

My issue is more related to EventsByTagQuery
When I am using this type of code 

```scala
val PersistenceQuery(system).readJournalFor[EventsByTagQuery(MongoReadJournal.Identifier)

RestartSource
      .withBackoff(minBackoff = 500.millis, maxBackoff = 20.seconds, randomFactor = 0.1) { () =>
            system.log.info("Starting stream for tag [{}] from offset []", tag)

            eventsByTagQuery.eventsByTag(tag, Offset.noOffset)
      }
      .via(killSwitch.flow)
      .runWith(Sink.ignore)
```

I can see in logs that the streams is regularly (depending on backoff) restarted, do you know why ? Am I missing something here or keeping stream open is not supported ?

Thanks in advance !

**Comment by scullxbones** [comment]
Hi @gael-ft 

No, that doesn't sound right.  That query should support keeping the stream open.

Which driver are you using?  And which version?

**Comment by gael-ft** [comment]
I am using ``akka-persistence-mongo-rxmongo`` version ``3.0.0`` with Akka ``2.6.4``.

**Comment by gael-ft** [comment]
I am closing the issue because looks like it was an issue between my mongo server and my application. Sad story here is that just the 'live' queries were not working.

Sorry for inconvenience.
