### ISSUE TITLE
Snapshotter doesn't recover when mongo connection encounters connection reset

### ISSUE THREAD

**Issue by ChanglinZhou** [scullxbones/akka-persistence-mongo#324]
<img width="1399" alt="Screen Shot 2020-04-09 at 12 08 38 PM" src="https://user-images.githubusercontent.com/1404188/78857131-28012e00-7a5b-11ea-9989-21642d4b0990.png">
<img width="1261" alt="Screen Shot 2020-04-09 at 12 08 58 PM" src="https://user-images.githubusercontent.com/1404188/78857133-29325b00-7a5b-11ea-8e5d-245fd8f551d0.png">

**Comment by ChanglinZhou** [comment]
version: 2.3.1

**Comment by scullxbones** [comment]
Hi @ChanglinZhou 

Can you provide more detail on `does not recover`?  I can't tell much from a stack trace.

Thanks!

**Comment by ChanglinZhou** [comment]
@scullxbones Thank you for the effort on this project.

The async call stack shows the closed mongo client is trying to sending data to server (createIndex)

It seems the mongo client doesn't cleanup the closed connections in the connection pool.
