### ISSUE TITLE
Slow recovery on DocumentDB for big event logs due to different index handling

### ISSUE THREAD

**Issue by an-tex** [scullxbones/akka-persistence-mongo#328]
Amazon DocumentDBs indexes work somewhat different to MongoDB. This leads to slow recovery on big event logs as retrieving the maxSequenceNr leads to a sort on the compound index `max_sequence_sort`. 

The workaround would be change the sort part of the query to also include the `PROCESSOR_ID`. Meaning in https://github.com/scullxbones/akka-persistence-mongo/blob/d7c1aacfe87329d149e9daaec23e12b4c2e57446/scala/src/main/scala/akka/contrib/persistence/mongodb/ScalaDriverPersistenceJournaller.scala#L218 
becomes
`.sort(BsonDocument(PROCESSOR_ID -> 1, TO -> -1))`

I guess the question I have is how important is compatibility to DocumentDB for this plugin? If it's not then it might still be worth mentioning it in the readme (or leaving it open as an issue for now?)

**Comment by scullxbones** [comment]
Hi @an-tex 

That looks like a backward-compatible change, so I'm game.  I don't plan on running DocumentDB through the test suite, but a small change like this one is an easy decision.

**Comment by an-tex** [comment]
Thanks for the fast reply @scullxbones ! I'll try to squeeze in a PR this week.

**Comment by scullxbones** [comment]
Released this with `v3.0.1`.  Thanks again for the contribution!
