### ISSUE TITLE
Suffixed collection migration tools should not empty metadata collection

### ISSUE THREAD

**Issue by gbrd** [scullxbones/akka-persistence-mongo#338]
If migration tool is launched when a journal collections is empty (for instance just cleaned + kept only one snapshot), the maxSequenceNumber in metadata is needed.

(+ bug in doc metadata is not a capped collection)

**Comment by scullxbones** [comment]
Hi - this is released with `v2.3.3` and `v3.0.2`.

Thanks for the report!
