### ISSUE TITLE
Sporadic recovery failure with reactivemongo and authentification

### ISSUE THREAD

**Issue by krchniam** [scullxbones/akka-persistence-mongo#34]
Hi,
I am using akka 2.3.12 with reactivemongo 0.11.6. Sometimes actor recovery fails with exception ```
reactivemongo.core.errors.DetailedDatabaseException: DatabaseException['not authorized for query on test.akkaPersistenceJournal' (code = 13)]```. I suspect that this is caused by ```RxMongoPersistenceDriver#connection``` implementation, because connection is created with pending autentification. When ```RxMongoJournaller``` tries to use this connection without completing autentification handshake, query fails on MongoDB side (sporadically, if handshake is slow). I can`t see any code which waits while authenticating connection and there is no guarantee, that this unauthentificated connection will not be used by ```RxMongoJournaller``` or ```RxMongoSnapshotter```.

My current workaround is custom implementation of ```MongoPersistenceExtension``` based on ```RxMongoPersistenceExtension``` which return connection after it is sucessufully authenticated. I can send pull request with my fix.

Thanks

**Comment by scullxbones** [comment]
Great - thank you for the report!  I'm not sure if this is an old bug or something that changed in 0.11 that i'm not accounting for.  If you'd like to send a PR, i'd be happy to integrate it.  Otherwise, I think this is enough information for me to start researching.

**Comment by krchniam** [comment]
Probably it`s old bug, based on my experience with reactivemongo in tests, behaviour is same as in 0.10. Most plugin ignores this, because they do not expect you will use connection so soon after ist creation. I will send PR.
