### ISSUE TITLE
EventsByTag support

### ISSUE THREAD

**Issue by scullxbones** [scullxbones/akka-persistence-mongo#37]
Support `EventsByTag` query in read journal

**Comment by marcuslinke** [comment]
@scullxbones Any ideas how to implement this already. As each event may have its own tags the most natural way is to store an optional subarray containing the tags for each event, right? With an index for this array the query performance should be suitable. WDYT?

**Comment by scullxbones** [comment]
Hi @marcuslinke -

Yes to some extent, the issue comes up where each document in the journal is a batch of events, all of which may have different tags.  So tags could be done at the event level, inside the array.  I think this is indexable off the top of my head.  The other approach I had considered would be to somehow materialize the events in their own collection by tag.  Definitely open on this one to a contribution or even just more ideas.

**Comment by marcuslinke** [comment]
@scullxbones I probably need `EventsByTag` query so currently looking into details. This type of query has to support the important `offset` parameter and I think about how this should be best implemented. When storing the tags as subarray of an event we might find all journal entries matching the requested tags, sort by `_id` and skip the first `offset` records. I don't know if this is a reasonable approach in the sense of performance. WDYT?

**Comment by marcuslinke** [comment]
Meanwhile I've found that the offset could be a mongo `ObjectId` representation, so instead skipping millions of records it should be possible to query for journal entries persisted after the given `ObjectId` offset.

**Comment by scullxbones** [comment]
Hi @marcuslinke - yes adding `> offset` to the query in mongo will work much better than `skip` for  `skip` > 1k,10k or so.

> find all journal entries matching the requested tags, sort by _id and skip the first offset records

> instead skipping millions of records it should be possible to query for journal entries persisted after the given ObjectId offset.

Are `_id`'s lexically monotonic on create timestamp?  Didn't realize that.  How usable would it be for a user to supply an `ObjectId` as offset, since that is pretty much hidden at all other times?

**Comment by filosganga** [comment]
@scullxbones @marcuslinke  The in the next version of akka-persistence (2.5.x) the offset is a type parameter. So it could be an ObjectId for Mongo, TimedUUID for Cassandra and so on.

**Comment by marcuslinke** [comment]
@scullxbones When using `EventsByTagQuery` the appropriate view receives events from multiple persistenceIds so it can't make use of the sequence numbers (which are related to single persistenceIds) to store its processing progress. The `Offset` as a global property of the stream that is passed via `EventEnvelope` must be used instead. This is needed for the initial replay of unprocessed journal events in the case of any failure / restart of that view. 

@filosganga At least akka-persistence v2.4.14 already defines that `Offset` type which is used here: https://github.com/akka/akka/blob/v2.4.14/akka-persistence-query/src/main/scala/akka/persistence/query/scaladsl/EventsByTagQuery2.scala 

So hopefully it should be possible to implement this `EventsByTagQuery2` with current akka release.

**Comment by marcuslinke** [comment]
Just found https://github.com/scullxbones/akka-persistence-mongo/issues/95 which is related I think. The monotonic "counter" mentioned is already there. Its the "_id" of the journal entry.

**Comment by filosganga** [comment]
@marcuslinke Yes I think to make sense to keep this and the #95 separated. The ObjectId timestamp part AFAIK is limited to seconds. It means that inside the same second the order of the event is given by machine id and counter. I don't think will be a problem as in a cluster environment a failure detection implies more than a second, but still something to keep in mind.

**Comment by scullxbones** [comment]
@marcuslinke so that `Offset` is available, you'd also need to make events of type `EventEnvelope2` (https://github.com/akka/akka/blob/v2.4.14/akka-persistence-query/src/main/scala/akka/persistence/query/EventEnvelope.scala). I see in the scaladoc where the expectation is that the user maintains their offset, so that could work.  I wonder what the execution plan looks like if we end up with a sort over `_id`.

@filosganga - I see what you mean, here's an SO answer describing it: http://stackoverflow.com/a/12100023/939126

**Comment by scullxbones** [comment]
Ah yes and I see #95 where i'm specifically referring to tag-based counters for offsets.

Now that I think about `_id` - there's an issue with that, right?  There's an `_id` per document, not subdocument, e.g.:

```javascript
{
  "_id": ObjectId("foo"),
  "pid": "bar",
  "from":1,
  "to":3,
  "events":[{
     "sn": 1,
     "p": "payload1",
     "tag": [ "baz", "qux" ]
   },{
     "sn": 2,
     "p": "payload2",
     "tag": [ "baz" ]
   },{
     "sn": 3,
     "p": "payload3",
     "tag": [ "qux" ]
   }]
}
```

In the case above the `_id` would be shared by `sn` 1,2 for tag `baz`.  The array of events is there to provide atomicity for `AtomicWrite` batches from akka-persistence.  Usually that batch size is 1, but it depends on how the user uses the akka-persistence api.

**Comment by filosganga** [comment]
@scullxbones I think the fact that the events, in the same atom, share the same id (and then timestamp) is not an issue, as they are been persisted at the same time.

The driver should be modified to return a Source[Atom] and the common Journal can filter out the event that does not have the searched tag.

I am not sure about performance in Mongo, will add a `tags` array to the atom, improve the query speed?

**Comment by scullxbones** [comment]
> I think the fact that the events, in the same atom, share the same id (and then timestamp) is not an issue, as they are been persisted at the same time.

Isn't the problem that two events share the same `Offset`?  Maybe i'm not understanding what the proposed solution is, but this would mean if a user received the first, but not the second, trying to replay from that `Offset` would get both elements again.

> The driver should be modified to return a Source[Atom] and the common Journal can filter out the event that does not have the searched tag.

> I am not sure about performance in Mongo, will add a tags array to the atom, improve the query speed?

With my understanding of the size of existing userbase journals, and in my own projects, it won't be feasible to perform a filtering in the scala code.  We'll need to leverage Mongo indices to filter down the data to a reasonable level.  An index on an embedded array would pare down the documents to those that contain the tag.   

An offset could also be embedded into the tag subdocument, this would assume the per-tag counters from #95.

```javascript
{
  "_id": ObjectId("foo"),
  "pid": "bar",
  "from":1,
  "to":3,
  "events":[{
     "sn": 1,
     "p": "payload1",
     "tags": [{
       "tag":"baz",
       "offset":11
     },{ 
       "tag":"qux",
       "offset":3 
     }]
   },{
     "sn": 2,
     "p": "payload2",
     "tags": [{ 
       "tag": "baz", 
       "offset":12 
     }]
   },{
     "sn": 3,
     "p": "payload3",
     "tags": [{ 
       "tag": "qux", 
       "offset":4 
     }]
   }]
}
```

**Comment by scullxbones** [comment]
And it may be simpler re: offset and sort to do another approach:

> The other approach I had considered would be to somehow materialize the events in their own collection by tag

The tradeoff becomes loss of atomicity, which I'm not excited about either.

**Comment by marcuslinke** [comment]
> Isn't the problem that two events share the same Offset? Maybe i'm not understanding what the proposed solution is, but this would mean if a user received the first, but not the second, trying to replay from that Offset would get both elements again.

@scullxbones Good point! Haven't thought about that yet. As the order of the replayed events never changes I dont think we need that offset at the tag level. I think we have to add an `offset` field at the event level instead that is either an ObjectId or a timestamp followed by the event index. The offset field is only needed when events are tagged so there is no need for migrating untagged events.

**Comment by filosganga** [comment]
@scullxbones Good point about receiving duplicate events. The offset should be unique for the nested event. It could be also the timestamp of the Atom followed by the event array index.

I wouldn't put the offset into the tag object, as the the offset could also be used when querying for allEvents or currentAllEvents.

Something like this should work:
```
{
  "_id": ObjectId("foo"),
  "pid": "bar",
  "from":1,
  "to": 3,
  "ts": <tmestamp>,
  "events":[{
     "sn": 1,
     "p": "payload1",
     "tags": ["baz","qux"]
   },{
     "sn": 2,
     "p": "payload2",
     "tags": ["baz", "offset"]
   },{
     "sn": 3,
     "p": "payload3",
     "tags": ["qux"]
   }
}
```

It could be back-compatible and using the `_id` if the `ts` is not available. We can always extract a ts from a Object id AFAIK.

**Comment by marcuslinke** [comment]
As I understand now we could use the timestamp of the journal entry (either by storing one ourself or extract it from the _id) and the index of the events to calculate an offset (string?) that is used when streaming the events to the view:

val offset = s"${timestamp}-${eventIdx}"

With this format we could make use of the timestamp part to query the journal for entries stored after that time and filter the events with index <= eventIdx out of the stream. Makes sense?

**Comment by scullxbones** [comment]
Extracting the timestamp from the `_id` isn't enough resolution (per second), I think the entire hex string is best.

Does mongodb sort `ObjectId` in a way that totally matches our expectations?  It seems like from [mongo BSON docs](https://docs.mongodb.com/v3.2/reference/bson-types/#objectid) the answer is "sometimes".  It helps (re: clock skew) that the plugin delegates the creation of the `ObjectId` to the mongo server, presuming the driver isn't doing something unexpected.

**Comment by filosganga** [comment]
@scullxbones my understanding is that is always the client that populates the _id field, never the server. But I may be wrong.

**Comment by marcuslinke** [comment]
@filosganga I think you are right here. The client generates the _id. But I think thats not a problem at all as we have to guarantee the order of events related to a specific persistenceId only. Each PersistentActor is served by a single journal plugin instance (so said a single local process / thread), so the resulting ObjectIds should be ordered correctly.

**Comment by filosganga** [comment]
@marcuslinke Yes, this was my initial thought as, taking over from one node to another node takes more time than 1 second. 

But, even if should not guarantee, the order across different persistence id, it is something nice to have. I am not sure if the machineId part is involved during the ObjectId comparison or not.

If it is, the events ordering in the same second will be affected by the machine that has written them. In that case, I think adding a timestamp field will be a better solution (and fallback to the ObjectId for previous events)

Regarding, the fact that, only one machine write in the same persistenceId, there are some edge cases where more than one persistent actor with the same persistence id is live on two different nodes for a short period of time. It may happen in a ClusterSharding configuration. This is the reason behind the writerUuid field in the PersistentRepr class.

**Comment by scullxbones** [comment]
Because the same tag can be applied to multiple actors, and because of common techniques for scaling (e.g. cluster sharding) there are no guarantees of the sequence of client-generated `ObjectId`s under any significant load because of 1s resolution timestamp, and originating host segments of `ObjectId`.  Because of clock skew, it is likely that client-generated timestamps can suffer a similar problem.  Thus it seems infeasible to expect time-sequencing of event-by-tag offsets.

That part needs documented.  Among other things, it will imply that `EventsByTag` and `CurrentEventsByTag` will behave differently.  It will be important for users to implement idempotent flows for tagged events so as not to be surprised when using both types of query.

I'll agree with both of you, let's go with storing the timestamp on the top level and the tags at the event level, using the index as an additional field on the Offset.  

@marcuslinke I'd like the Offset to be modeled in the scala as a case class at a minimum having two fields rather than having to serialize/deserialize a string.  It should be opaque to the user so we can change on the inside as needed without impact.

We'll need a new index on tag and timestamp, which should be either sparse or partial.  Sparse would give backward compatibility for 2.6, 3.0 ~ let's go with that.  There should be no compatibility or migration issues given we're adding fields and an index, which is good news.

WDYT?

**Comment by marcuslinke** [comment]
@scullxbones I agree. Would like to prevent any migration needs for the new query type so timestamp field should be written only for tagged events and use sparse indices.

However there is another question open. How the user would be able to pass the event tags to the journal? The documentation mentions [Event Adapters](http://doc.akka.io/docs/akka/current/scala/persistence-query.html#EventsByTag_and_CurrentEventsByTag) but I wonder how this should work in our case for BSONDocuments passed directly to the `persist()` methods? Maybe we have to change something here?

Currently serialization/deserialization to/from BSONDocuments is done in the application code. Maybe we have to force the use of custom serializer/deserializer to support this in the future so the serialization stuff as well as the tagging (via EventAdapters) can be handled within the journal plugin.

**Comment by filosganga** [comment]
@marcuslinke I don't see why we cannot add the timestamp to all events, of course, old events will not have that, but it is fine. In this way, we can use the offset also for allEvents and currentsAllEvents queries.

For the BSONDocuments passed directly to the persist does not change much. The user has to implement an EventAdapter in which it will examine the content of the BSONDocument and wrap it in the Tagged case class. The same will happen for the not BSONDocument event.

**Comment by marcuslinke** [comment]
>  old events will not have that, but it is fine

How this should work? If the timestamp is not there we cant order by it in the query. 

> The user has to implement an EventAdapter in which it will examine the content of the BSONDocument

Although its possible examining already BSON serialized events is a bit ugly I think. But thats only my personal opinion. However maybe we could support passing of `akka.persistence.journal.Tagged` wrapper directly? It would be easier for journal users to simply wrap its events into `Tagged`. I wonder why the docs prefer implementation via EventAdapters ("Some journals may support tagging via EventAdapters. The journal may support other ways of doing tagging").

**Comment by marcuslinke** [comment]
Anyway, beside this it seems there is no way to create an empty `BSONTimestamp()` with rxmongo, so maybe we MUST use `_id` as ordering criteria.

**Comment by filosganga** [comment]
> How this should work? If the timestamp is not there we cant order by it in the query.
Ca we have order by `timestamp` then `_id`? Will it work?

My feeling is that tagging the event should not be a responsibility of the PersistentActor but rather the Journal plugin should do that. Also because the PersistentActor code will become a little bit clumsy:

```
persist(Tagged(event, Set(tag1, tag2, tag3)){ 
   case Tagged(event, _) => ...
}
```

I guess it is the rationale behind the Akka doc. 

In addition It will make easier to replace plugin, as the PersistenceActor code will not change

**Comment by marcuslinke** [comment]
@filosganga I've implemented direct passing of `Tagged` for the first time. As there seems currently no event adapters support I will leave this for later. 

@filosganga @scullxbones Against my former statement it would be possible to generate timestamp values at the db side and use that as ordering criteria. However there will be some problems with this:

1. Need to read the journal entries after insert to get the db timestamp for passing it to the view side as offset
2. There is a problem with the current implementation of realtime queries via capped collection. Each journal entry is inserted into the journal collection and also in the capped collection which is the datasource for the realtime queries. When using db generated timestamps these will differ between the journal and the realtime collection resulting in passing inconsistent offsets to the view side.
3. Beside this I'm not sure how mongo itself handles timestamp generation in a cluster. Will the timestamp used be synced between cluster nodes?

If we accept 1. we could pass the db generated timestamp from the journal collection to the realtime capped collection of course. But I'm not sure if this would be good for performance reasons. Maybe we need a stronger approach for the ordering criteria (via findAndModify) ? Any suggestions?

**Comment by filosganga** [comment]
Good job @marcuslinke! I was wrong on this point, passing direct `Tagged` is completely fine. As an eventual `EventAdapter` will let it pass trough the journal. You don't need to do anything else.

Regarding the timestamp, the Cassandra plugin takes a different approach: It generates the timestamp client side and passes it to the DB. I think, overall it is a better approach, as in the Akka cluster the time MUST be in sync (ddata and other bits do not work well otherwise). Also given the 3rd point, It will be a safer approach anyway. I will avoid by any mean reading back the inserted row.

Looking forward to try it.

**Comment by scullxbones** [comment]
Yes client-side generation of timestamp makes sense to me as well.  And sorry couldn't respond earlier, but the plugin needs to support `Tagged` directly.  If either the user sends directly from the `PersistentActor` or the `EventAdapter` sits between the PA and the plugin, it looks the same to us.  It seems that's where we ended up so 👍 

The contents of a `Tagged` event should be processed as before this enhancement, with the extra tagging logic applied.  I don't think a new "type hint" should be created for tagged events.

This is one of (last of?) the big feature holes for `PersistentQuery` - thanks much for taking it on @marcuslinke !

**Comment by marcuslinke** [comment]
> Regarding the timestamp, the Cassandra plugin takes a different approach: It generates the timestamp client side and passes it to the DB. I think, overall it is a better approach, as in the Akka cluster the time MUST be in sync (ddata and other bits do not work well otherwise)

So we could do the same. Generate a timestamp client side and use that as the ordering criteria. But I'm not sure if we should really use a timestamp with milliseconds resolution. This will lead to a problem if there is just a little time skew between nodes: If one node stores a journal entry (B) with a timestamp just a millisecond BEFORE an already published journal entry from another node (A) this might result in data loss in the view when the view is recovering with an offset that references A.

Maybe it would be better to use a timestamp with seconds resolution (as contained in `_id`) and restore the view starting from all events within that second? With this approach we would accept doubled events in the view of course but I think the same counts when using milliseconds resolution.  

@filosganga @scullxbones Any suggestions?

**Comment by filosganga** [comment]
>
> I think it is an acceptable drawback, I don't see too much problem about
that. Keep in mind that Cassandra uses the nanosecond resolution.

**Comment by marcuslinke** [comment]
So using a timestamp regardless which resolution we choose we would accept data loss or doublicated events in the view. In my oppinion this is hardly acceptable. Maybe we should better implement something like this  https://docs.mongodb.com/v3.0/tutorial/create-an-auto-incrementing-field ?

**Comment by marcuslinke** [comment]
Currently looking at cassandra plugin implementation. There are [EventsByTagPublisher](https://github.com/akka/akka-persistence-cassandra/blob/master/src/main/scala/akka/persistence/cassandra/query/EventsByTagPublisher.scala) and [EventsByTagFetcher](https://github.com/akka/akka-persistence-cassandra/blob/master/src/main/scala/akka/persistence/cassandra/query/EventsByTagFetcher.scala). Seems when using timestamps we would need a comparable complex logic that tries to guarantee consistent ordering of events at the view side.

**Comment by scullxbones** [comment]
Ah just looking at the cassandra plugin, they require `akka-cluster`?  I'd rather not put that on the mongo plugin users, that's why there's a `realtime` collection + local event publisher, to avoid just that complexity.  Agreed it's complex.

@marcuslinke  - can you help me understand why we'd have data loss or duplicated events?  I can see how the sequence of events written may not match the sequence read-via-`EventsByTag`, but not the other two - which would be show stoppers, agreed.

**Comment by marcuslinke** [comment]
@scullxbones A view persists the current offset when receiving the (tagged) events it is interested in to keep track of the events it has already processed. If we use a timestamp for the offset (which is in fact the only scalable way of creating one) we have to deal with clock skews between cluster nodes:

> This will lead to a problem if there is just a little time skew between nodes: If one node stores a journal entry (B) with a timestamp just a millisecond BEFORE an already published journal entry from another node (A) this might result in data loss in the view when the view is recovering with an offset that references A.

Additionally there could be multiple journal entries within the same timestamp. Which one would be addressed by a specific offset especially if you think of the possibility that an additional event for that timestamp might occur later? In this case we probably have to replay ALL events with that specific offset which may lead to events duplicated in the view.

The problem is not just related to recovering. The same counts when a persistent actor is migrated from one node to another (because of a node failover for example). 

This is what [EventsByTagPublisher](https://github.com/akka/akka-persistence-cassandra/blob/master/src/main/scala/akka/persistence/cassandra/query/EventsByTagPublisher.scala) TRIES to solve. It "just" keeps track of the continuous incrementation of the sequence numbers of all persistent actors in the stream, filters duplicates or delays the propagation to the view eventually because there might be a chance that a missing sequence number still arrives within that delay.

**Comment by filosganga** [comment]
> The problem is not just related to recovering. The same counts when a persistent actor is migrated from one node to another (because of a node failover for example).

I am not sure about that, they will be ordered by sequence number as they belong to the same persistence id.

> Additionally there could be multiple journal entries within the same timestamp. Which one would be addressed by a specific offset especially if you think of the possibility that an additional event for that timestamp might occur later? In this case we probably have to replay ALL events with that specific offset which may lead to events duplicated in the view.

This happens in Cassandra as well, if you don't use the UUID offset. To be fair events should be idempotent, and so receiving duplicate events should not cause too much harm. But this should be clear to the user. If we can avoid it, of course, will be better.

The EventsByTagPublisher tries to solve this and a different problem as well: Cassandra plugin uses the materialized view. They are eventual consistent so some events written in some node can not be available for some time. The EventsByTagPublisher will check if there are holes in a persistence id, it there are it will stop waiting for the missing events.

Also The Cassandra plugin does not guarantee the absolute order of the events, from different persistenceId. So you may have shuffled events, but events in the same persistenceId are instead monotonic. This is because you have the sequence nr on wich you can reply on to reorder the events.

I think it is the best we can achieve without screwing up performances.

**Comment by marcuslinke** [comment]
>>  The problem is not just related to recovering. The same counts when a persistent actor is migrated from one node to another (because of a node failover for example).

> I am not sure about that, they will be ordered by sequence number as they belong to the same persistence id.

Just to be clear here: The problem might occur if there is a clock skew between these nodes. (event with seqNr 2 is timstamped before event with seqNr 1)

**Comment by filosganga** [comment]
> Just to be clear here: The problem might occur if there is a clock skew between these nodes. (event with seqNr 2 is timestamped before event with seqNr 1)

I don't think it does matter: In a `PersistentActor` the recovery query will not be sorted by timestamp but by sequence nr.

It will only matter for `EventByTag` query (and `AllEvents`), don't you agree?

**Comment by scullxbones** [comment]
@marcuslinke ok i see what you mean with duplication:

> Additionally there could be multiple journal entries within the same timestamp. Which one would be addressed by a specific offset especially if you think of the possibility that an additional event for that timestamp might occur later? In this case we probably have to replay ALL events with that specific offset which may lead to events duplicated in the view.

So on write, we'll create the timestamp.  We can look into a migration in the future to back-propagate this (and potentially add tags, and add insertion order sort to `AllEvents`), but don't want to bite off too much now.  When a user runs the query they can hold onto the timestamp they care about, and you're right - it may cause them to see "more events" than they'd like.  For this initial release, idempotency/"at least once" will be a requirement for users of `EventByTag`.  It can cause duplication on multiple runs, but not lost data since the only way a user will know the offset is via running `EventByTag` at least once.

@filosganga I agree, it would only affect those two queries, not recovery.  `sequenceNr` isn't leaving, that needs to continue to drive recovery - that's a critical part of `akka-persistence` behavior.

**Comment by scullxbones** [comment]
I think i'm going to take a swing at this.  Let me know if any work is still being done.

**Comment by marcuslinke** [comment]
@scullxbones Sorry, hadn't and currently don't have any further time for this. As I remember the state of my local sources were rather experimental so they wouldn't really help you I guess.

**Comment by scullxbones** [comment]
@marcuslinke no problem!  Thanks for spending the time you did.

**Comment by scullxbones** [comment]
Fixed in `2.0.3`

**Comment by yahor-filipchyk** [comment]
Question: will events stored in the same atom (document) have the same offset? So if I'm saving offset after **every** processed event and the stream dies when only part of the events from the same atom were processed, will the next stream created after recovery start with the next atom skipping unprocessed events from the previous atom?

**Comment by scullxbones** [comment]
> will events stored in the same atom (document) have the same offset?

Yes they will have the same offset, and when an offset is supplied, it's used as a part of a `$gt` query.  I don't think it's likely the stream would die intra-offset, since all of the events in the atom are in memory, but I suppose it's possible.

What if the logic is changed such that the previous offset is saved only when the offset changes?

**Comment by yahor-filipchyk** [comment]
Yeah, I guess I'll have to change the logic to avoid skipping events, just didn't know about this limitation earlier
