### ISSUE TITLE
Support for latest mongo-java-driver

### ISSUE THREAD

**Issue by srikanthm-1** [scullxbones/akka-persistence-mongo#389]
Hi,
We are using the latest mongo driver (4.1.0) and that causing the akka-persistence-mongo to fail. The reason seems to be due to the current version referencing some unavailable methods in the latest version of the mongo driver. For eg. It references an unavailable method [maxWaitQueueSize](https://github.com/scullxbones/akka-persistence-mongo/blob/master/scala/src/main/scala/akka/contrib/persistence/mongodb/ScalaDriverSettings.scala#L50) which has been made unavailable since mongo driver 4.x. More details [here](https://github.com/mongodb/specifications/blob/master/source/connection-monitoring-and-pooling/connection-monitoring-and-pooling.rst#why-are-waitqueuesize-and-waitqueuemultiple-deprecated). Is there a plan to upgrade the mongo-driver version used?

**Comment by scullxbones** [comment]
Hi @srikanthm-1 

I have been working on a side branch to fixes all the breaking changes in the mongo driver.  That's still underway and I am not making rapid progress on it.  I would be happy to review a PR that fixes the breakage which consistently passes the test suite.  

That said, I'll make another push this weekend to get through the driver upgrade.

**Comment by scullxbones** [comment]
Fixed with v3.0.5

**Comment by srikanthm-1** [comment]
Hi @scullxbones ,
Thanks a lot for fixing this. We haven't upgraded to Akka 2.6 in our app. Is there any change this change could be patched in the 2.x version?

**Comment by scullxbones** [comment]
Hi @srikanthm-1 -

Sorry, I'm only back-porting serious breaking bugs to the `2.x` series at this point.

The upgrade to `2.6` isn't too bad, can stay on `Classic Actors` for now.  I see the akka team is calling recently released `2.5.32` one of the last of `2.5` series FWIW.

**Comment by srikanthm-1** [comment]
Yup, unfortunately we have Typed Actors in our code and the akka upgrade wasn't that straight forward, but after the akka upgrade using v3.0.5 worked. Thanks @scullxbones
