### ISSUE TITLE
Support mapping persistenceId to collection name

### ISSUE THREAD

**Issue by scullxbones** [scullxbones/akka-persistence-mongo#39]
* Allow for user-specified mapping of `persistenceId` to collection name
* Could be used to support different mongodb sharding approaches per Actor type

**Comment by alari** [comment]
How can I help with this feature?

**Comment by scullxbones** [comment]
Help would be welcome - if you want to submit a PR, that would be great.  I wasn't planning on getting to this one for a little while - I want to get the live tailing queries running first.

The trick with this one (I think) is we'll need to store some metadata about the mapping in a collection - this is so when we either recover or append (or query for the new read journal queries), we know which collection needs to be queried.

**Comment by jftregor** [comment]
Hello there,

I'm working for a project where we need to separate journal collections depending on _some part_ of  `persistenceId`.

Our `persistenceId` looks like "Namespace/**namespace**/some/path/..." and we need to store events by **namespace**, in journal collections named "akka_persistence_journal_**namespace**".

Actually, we use the default journal name "akka_persistence_journal" that we suffix with an underscore character followed by the **namespace** extracted from `persistenceId`. We do the same for snapshots... But we did not change realtime and metadata.

So, I updated your plugin (code and unit tests, but only for Casbah) and it works like a charm for us. This is not really a mapping, but it could be a first step...

I guess I'm going to submit a Pull Request (my first ;-)) as soon as I update the readme file with some more clearer explanation...

**Comment by scullxbones** [comment]
Ok - if the user can provide a custom function that takes a `persistenceId` and returns a collection name, that should cover the requirement.  I'm not sure yet how to deal with what to do if the mapping changes other than the metadata collection I mentioned above.  It may be for a first cut that the mapping function cannot change, including documentation of such.

I'm not in favor of releasing a generic change for a single driver - I like to keep feature parity between the two.  Can the PR also update the RxMongo driver?  I've found that if I can hang most of the functionality off of the common classes (e.g. `MongoJournal`), then it makes supporting multiple drivers simpler.

**Comment by jftregor** [comment]
Hello there,

Some news: 

- I already provided such a function you mentioned above. Basically, the user has to extend some trait and override a "getSuffixfromPersistenceId" method...
- I finally added a chapter at the end of akka24.md file to provide documentation
- I guess the PR will also update the RxMongo driver :-)

Just let me finish some unit tests, I now only have to append a few ones to JournallerSpec and SnapshotterSpec on the RxMongo side and that should be ready.

**Comment by JeanFrancoisGuena** [comment]
Hello there,

Sorry for the delay, but I had to wait for a GO from my company before actually submitting the PR. This is a process I was not aware of, plus we are in the middle of vacations and many people were not at the office (including me) these days...
Anyway, it's done now, I hope that you don't have to wait for some GO to review and accept the PR ;-) ... and that you don't have to change your GitHub login for a more "official" one too ;-)

**Comment by scullxbones** [comment]
No worries on the delay, thank you for the PR submission!  It will take me a couple of days to get through it.  And yes I have no such restrictions, so that should make my side a little quicker :)

**Comment by scullxbones** [comment]
Closed by #118
