### ISSUE TITLE
"appName" URI option is overriden by hardcoded "akka-persistence-mongodb" application name

### ISSUE THREAD

**Issue by fguerout** [scullxbones/akka-persistence-mongo#407]
Hi,

Thx for great library!

"appName" URI option (https://docs.mongodb.com/manual/reference/connection-string/#urioption.appName) is overriden by hardcoded "akka-persistence-mongodb" application name in scala driver: https://github.com/scullxbones/akka-persistence-mongo/blob/master/scala/src/main/scala/akka/contrib/persistence/mongodb/ScalaDriverPersistenceExtension.scala#L28

Should we default to "akka-persistence-mongodb" but keep "appName" option safe in URI ?

Thx in advance,
Br,

**Comment by scullxbones** [comment]
@fguerout - if you can open a PR with that commit i'll get it released.  

Can you give any more details on this, specifically on "header not correctly read":

> I've tried to switch to rxmongo instead (which does not have this issue) but I'm facing another issue with snapshot replay (header is not correctly read)

Would like to get an issue tracking that problem, the drivers should be interchangeable from the plugin's perspective.

**Comment by fguerout** [comment]
@scullxbones - thx, just created https://github.com/scullxbones/akka-persistence-mongo/pull/409

Regarding decoding issue (header not correctly read), I'll isolate it in a simple example project, and I'll share it with you.

**Comment by scullxbones** [comment]
Released with `3.0.6`

Thanks for the contribution!
