### ISSUE TITLE
Documentation update (for akka 2.4.0) 

### ISSUE THREAD

**Issue by wofr** [scullxbones/akka-persistence-mongo#50]
Maybe you can add a hint to your documentation that  the reactive-mongo/casbah dependency must be added to the project as well because in your build.sbt casbah/reative-mongo is marked as provided.

Simply adding your library those otherwise not work.

By the way great work!

Wolfgang

**Comment by scullxbones** [comment]
Yep I lost that sentence in the upgrade.  Thanks for reporting!

**Comment by scullxbones** [comment]
Should be fixed.  Thank you for taking a minute to let me know.
