### ISSUE TITLE
Class.forName fails to find class in deserialization (was readjournal.allEvents not returning all the events)

### ISSUE THREAD

**Issue by axiom24** [scullxbones/akka-persistence-mongo#52]
Only some events are returned by allEvents and a different set of events are returned by currentPersistentIds. Using latest rxmongo plugin

**Comment by scullxbones** [comment]
Hi @axiom24 thanks for the report.  Given that this code is not as battle-tested yet, there's bound to be issues.  I have some basic tests in place which are passing, but that only means I could be missing a test case.  I could use some more information though, anything about which events are missing from the `allEvents` query?  

I also don't understand:
> different set of events are returned by currentPersistenceIds

`currentPersistenceIds` should only return the current set of `persistenceId`s in the journal - it should not return any actual events (where an event is persistenceId +  sequenceNumber + payload)

Also can you share how you are draining the stream?

Thanks!

**Comment by scullxbones** [comment]
Ha, apparently I need to set up a gitter.im room here :)  ... I see your conversation with @matheuslima in akka/akka.

To answer my last question - it looks like this is your code [pastebin](http://paste.ubuntu.com/12695310/)

To answer one of your questions, I don't think it should matter that the journal is writing on a different node, as long as you don't have a timing problem.  As soon as the live events ticket is done this will no longer be a potential issue.

The one thing I thought of that the test probably doesn't cover is event batching.  When events come in slow, akka doesn't batch them together.  Are those the events you're missing?  Ones that are batched together?  You would see this in the journal if the `from` and `to` fields were different.

**Comment by matheuslima** [comment]
I ever had some issues with batch insertion. If I send some events fast to persistence, the events are not are send to mongo, although  the persistence confirm the insertion. Maybe the problem be default max size batch. But, theoretically the batch size should be equals 1 and increase according to rate of incoming events.

**Comment by axiom24** [comment]
As i mention on gitter I could view the events in the mongo db journal but are not returned by allevents, So I dont think batch size is the problem here.

**Comment by scullxbones** [comment]
@matheuslima that would be a big problem if I understand you correctly.  I think you're saying that the plugin drops (ignores) some events when under load.  Let me know when you have enough information and please submit a ticket for that one.

@axiom24 can you clarify whether you're seeing batches of events, and also whether you're seeing all `persistenceId`s in `allEvents`?  Or is `allEvents` missing some `persistenceId`s?

**Comment by axiom24** [comment]
@scullxbones for eg if I created some users and persisted those events.. when I do allevents() i dont get those events, instead I get shardHomeallocated and all those events. But if I do currentpersistenceIds, I do get some of those user created events.

What else can I tell to clarify?

**Comment by scullxbones** [comment]
Ok so for `allEvents` you get *only* infrastructure events like from cluster sharding (I assume that's what you mean), and *no* application level events (e.g. create user).  

For `currentPersistenceIds` you get the expected application persistence ids + infrastructure ones.

> What else can I tell to clarify?

I'm just trying to get to a repeatable test case.  I'm not sure yet exactly how to duplicate your problem.

If you use the casbah implementation on the read side, do you see the same issue?

**Comment by axiom24** [comment]
@scullxbones yeah thats the issue.
> If you use the casbah implementation on the read side, do you see the same issue?
Havent tried that.

**Comment by axiom24** [comment]
> I'm just trying to get to a repeatable test case. I'm not sure yet exactly how to duplicate your problem.

Here is waht I am doing. My readJournal is in a receiver method of an actor where it tries both allevents and currentpersistenceids stuff. 
The persistence part is on a different machine which persists events like UserCreated using simple persist() method.

**Comment by axiom24** [comment]
@scullxbones I noticed that I get this in log.info
a.c.p.m.RxMongoDriver - No configuration-specific overrides found to apply to driver

This has anything to do with the problem?

**Comment by scullxbones** [comment]
No that's fine.  This is the addition in `1.0.6` that I need to write a bit of documentation for.  It allows you to run multiple versions of this plugin with different configurations.

Do you not see the same issue if the read journal and persistence (write side) run in the same actor system?

FYI I created a [gitter room](https://gitter.im/scullxbones/akka-persistence-mongo) for this project

**Comment by axiom24** [comment]
> FYI I created a gitter room for this project
Joined the room. Posted there.

**Comment by scullxbones** [comment]
ended up being same ultimate issue as #45 

research whether thread context classloader can fix.

**Comment by scullxbones** [comment]
Fixed in 1.0.9
