### ISSUE TITLE
Remove possibly buggy bulk inserts from rxm driver

### ISSUE THREAD

**Issue by scullxbones** [scullxbones/akka-persistence-mongo#54]
from gitter:
@gbrd
> tested : with casbah : create some event => replay ok - switch to rxmongo => replay ko
> with rxmongo : create some events - replay KO - switch to casbah => replay ok

> it only replays around 100 messages
> I just noticed I have at startup an error log message : reactivemongo.core.actors.MongoDBSystem - 
> The entire node set is unreachable, is there a network problem?

**Comment by gbrd** [comment]
note: startup error log message is not systematic
