### ISSUE TITLE
Consumer has to share class paths with producer

### ISSUE THREAD

**Issue by HannesSchr** [scullxbones/akka-persistence-mongo#60]
Hi scullxbones,

We seem to have a problem with your type hinting during persistence - or more accurately during reading of persisted events.

We have a microservice-architecture and thus, producer and consumer have their events in their own packages via copy&own. The problem arises when a consumer tries to read the journal and fails to load the hinted class as it is not in the classpath.

The resulting stacktrace is something like this:

```
java.lang.ClassNotFoundException: com.enterprise.producer.myconsumerservice.es.event.MyEntityCreatedEvent
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at org.springframework.boot.loader.LaunchedURLClassLoader.doLoadClass(LaunchedURLClassLoader.java:170)
    at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:136)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:264)
    at akka.contrib.persistence.mongodb.Payload$.apply(MongoDataModel.scala:114)
```
(The consumer's package starts with `com.enterprise.consumer`)

Prior to this upgrade, the serialized payload was handed into our JSerializer as byte array and we got the (simple) class name from it. The serializer then had a mapping of simple class names to local classes in the consumer package. This also enabled for ignoring events that the consumer does not actually need. Furthermore, the events do not have to have the same name on both sides and multiple producer events can be mapped into a single generic event.

Does your framework support our scenario in the new version or are we missing something?

Our first idea to tackle this problem was to implement a generic class in a base package that all events are mapped to prior of persisting, something like

```
public class PersistedEvent implements Event {
   private byte[] payload;
   private String simpleClassName;
   ...
}
```

but I am not entirely sure wether this would be easily auto-upgradable (which we need as we already have real data which we must not throw away).

Any ideas on this?

**Comment by scullxbones** [comment]
Hi and thanks for the report!  I had never considered this use case of events being interpreted differently based on the whether they're written or read.  Am I correct in understanding that the producers are `PersistentActor`s and the consumers are `PersistentView`s?

I have a question, which upgrade are you referring to?  As in, what are the before and after versions?  I don't know if you mean 0.x -> 1.y or 1.0.x -> 1.0.y.

If you're using akka 2.4, there is a concept called [EventAdapters](http://doc.akka.io/docs/akka/2.4.0/scala/persistence.html#Event_Adapters) which should be a good integration point for your `JSerializer`, but auto-migration will be a problem in that case.

There is also some good documentation [here](http://doc.akka.io/docs/akka/2.4.0/scala/persistence-schema-evolution.html) which may be applicable

**Comment by HannesSchr** [comment]
Hi, thanks for your reply.

Yes, our producers are `PersistentActor`s and consumers `PersistentView`s.

The upgrade I am referring to is the 0.4 -> 1.0 upgrade as we wanted to upgrade our Akka-version from 2.3 to 2.4.

The EventAdapters, as far as I understand it, would be basically the mentioned idea of `PersistedEvent` - to be readable by any service, the EventAdapter would have to store into a class that everybody knows (albeit this would use possibilities directly provided by Akka itself). But as the auto-migration is something we absolutely need, this is most likely not a solution.

I think the easiest fix for this would be an option to ignore the new type hint on reading (and thus provide the old behavior).

How complicated would an option like this be?

**Comment by scullxbones** [comment]
Ignoring the type hint isn't an option, but I have the following idea:

I think this can be accommodated with a special configuration option which will cause event serialization to go back to serializing the entire `PersistentRepr` with its own special hint (legacy or something like it).   This would fully delegate to akka serialization, rather than treat some BSON-representable types specially.

This depends on my assumption that your mentioned `JSerializer` is an akka-serialization `Serializer`.  If it isn't, then it would be helpful to understand more about how it works / integrates.

**Comment by HannesSchr** [comment]
Your assumption is correct - the `JSerializer` is the Java-API for the akka-`Serializer` and is integrated via `akka.actor.serializers` as usual.

The special option sounds good and would be greatly appreciated. Am I correct that the auto-migration would work with this?

**Comment by scullxbones** [comment]
> Am I correct that the auto-migration would work with this?

Yes, assuming that you start with your 0.x journal, and enable the new configuration setting before starting up with auto migration enabled.  You'll be able to inspect the journal and see the new legacy type in place after the migration has happened.

**Comment by sourcekick** [comment]
I vote for the idea of having a (configuration) option in the plugin to enable event consumption without JVM-based type safety regarding the concrete Event classes.

I would not call it a legacy option, because I think that decoupled event producers and consumers with respect to concrete Event class files and Event properties (without the need for special technical Adapters) can be viewed as a common pattern.

**Comment by scullxbones** [comment]
Fixed in `1.0.10` - To try it out, you can add the following to your `application.conf`:

```akka.contrib.persistence.mongodb.mongo.use-legacy-serialization = true```

@HannesSchr, please let me know how your testing goes and if this solves the problem.

**Comment by HannesSchr** [comment]
Hi,

A quick first test looks good (2 out of 20+, started on a clean mongo). Still have to run a big test and check the auto-upgrade, but for now it looks very promising. I'll let you know how it goes.

Thanks a lot for now.

**Comment by HannesSchr** [comment]
Tested on full scale: Your fix works great, but during data migration I found another problem during data migration.

It has nothing to do with this original issue so I'm opening a new one.
