### ISSUE TITLE
Data migration fails on filled database due to missing fields

### ISSUE THREAD

**Issue by HannesSchr** [scullxbones/akka-persistence-mongo#70]
Hi,

I encountered a problem during automatic data migration on a database. As old entries do not have the `from`- and `to`-fields, the respective index-creation fails during startup (as the new non-sparse index is `{pid_1_from_1_to_1}` - the same pid exists multiple times and thus the combination `pid-null-null` breaks the index immediately. 

As far as I can tell (my scala is quite rusty), the problem arises due to 
akka/contrib/persistence/mongodb/MongoPersistence.scala : LL. 89-99.
Here, you create the index _before_ you migrate the data which fails due to the missing fields. This ordering seems logically wrong, although I might be missing something.

We tried using a mongo-script to manually insert the fields beforehand, but due to size of our database this script would take almost a day to complete, which is not acceptable.

Would a simple swap of the automatic upgrade and the `ensureUniqueIndex(...)` solve the problem?

**Comment by scullxbones** [comment]
Yep that should do it.  If the upgrade fails for any records, you can still get the same issue.  But at least it would have to fail first.

**Comment by scullxbones** [comment]
You're right that the change is simple, but i'm seeing some strange behavior on the rxmongo side.  Still working through that.

**Comment by scullxbones** [comment]
The fix is available in `1.1.2`
