### ISSUE TITLE
Failover strategy when connecting to the DB ?

### ISSUE THREAD

**Issue by ticofab** [scullxbones/akka-persistence-mongo#84]
There is an ongoing problem with RxMongo: upon connecting to a DB, it might happen that methods such as `reactiveMongoApi.db` return before having actually connected. This is discussed here https://groups.google.com/forum/#!topic/reactivemongo/x3OZ6-hIIXk 
This problem appears in this project, up to 1.1.5, where for instance the first attempt to store an event in the journal always causes 

```
reactivemongo.core.errors.DetailedDatabaseException: DatabaseException['not authorized for query on pe-event-jorunal.akka_persistence_journal' (code = 13)]
``` 
This issue is being addressed in the 0.12 branch, where we can deal with `Future[DefaultDB]` instead.
For prior versions (like the 0.11 branch) one workaround is to use a FailoverStrategy while connecting. This is maybe not worth fixing now, but it's maybe something to keep in mind when bringing this great library to the RxMongo 0.12 stage :)

**Comment by scullxbones** [comment]
As of `1.1.6`, failover strategy can now be customized as [documented here](../blob/master/docs/akka24.md).  Give it a try and let me know if it helps.  I know it's just a workaround for now.

Thanks for reporting!

**Comment by ticofab** [comment]
Wow - thanks for addressing it so quickly!
