### ISSUE TITLE
JournalRangeQuery seems to override its own field

### ISSUE THREAD

**Issue by HannesSchr** [scullxbones/akka-persistence-mongo#88]
Hey,

While analyzing our mongo log, I stumbled upon a query that uses the `pid` and an `$lte` on the `from`. The only query I'm able to find in the code is
```
(PID $eq pid) ++ (FROM $gte from) ++ (FROM $lte to)
```
In particular, the `$gte`-part seems to be missing from the query.

I found an example in the mongo API where such a case is demonstrated, but the query is built slightly different:
```
(PID $eq pid) ++ (FROM $gte from $lte to)
```

Am I missing something or is this really a bug in the code?

If the latter is the case, I already created two pull requests.

https://github.com/scullxbones/akka-persistence-mongo/pull/86
https://github.com/scullxbones/akka-persistence-mongo/pull/87

**Comment by HannesSchr** [comment]
My proposed query was not quite correct, but is now updated in the corresponding PR.

It should be
```
(PID $eq pid) ++ (FROM $lte to) ++ (TO $gte from)
```

Looking at you original query, this also seems to be what you've originally intended.

**Comment by scullxbones** [comment]
Applied in release `1.1.7`.  Thanks for the contribution!

It took WAY longer than it had to due to a realm change in sonatype oss breaking sbt publishing :rage: ... https://issues.sonatype.org/browse/OSSRH-13401 ... maybe it's time to look at bintray.
