### ISSUE TITLE
Long running queries for large event collections

### ISSUE THREAD

**Issue by michaelom** [scullxbones/akka-persistence-mongo#89]
- Version: 1.1.7
- Casbah Driver

Hi scullxbones,

after fixing the range query with 1.1.7 (which we appreciate) we can observe long running queries on large event collections:

```query somecollection.events query: { $query: { pid: "SomePid", from: { $lte: 569551 }, to: { $gte: 569549 } }, $orderby: { from: 1 } } planSummary: IXSCAN { pid: 1, from: 1, to: 1 } ntoreturn:0 ntoskip:0 nscanned:xxx nscannedObjects:3 keyUpdates:0 writeConflicts:0 numYields:xxx returned:3```

This query can take up to 2 seconds.

If the same query is executed with `$orderby: { to: 1 } }`, performance is in the 2-digit `ms` space:
```query somecollection.events query: { $query: { pid: "SomePid", from: { $lte: 569551 }, to: { $gte: 569549 } }, $orderby: { to: 1 } }```

That _should_ yield the same result, right?

Also, we noticed that CasbahPersistenceJournaller and CasbahPersistenceReadJournaller use different queries:
`.sort(MongoDBObject(FROM -> 1))` vs 
`.sort(MongoDBObject(PROCESSOR_ID -> 1, FROM -> 1))`

**Comment by scullxbones** [comment]
Ah.  The fields are in the wrong order for the sort.

If there were an index that was `{pid:1,to:1,from:1}` that query would take a couple of ms.  I think it's probably less disruptive to sort on `to` in the query instead.

And both read journal sorts are wrong as I am looking at it, both for `CurrentEvents...` and `AllEvents...`

**Comment by michaelom** [comment]
We tried `{pid:1,to:1,from:1}` and it performed faster. Not as fast as a sort on `to` however. But that was not a real benchmark and there could have been other factors.

**Comment by scullxbones** [comment]
Hi @michaelom - the sorts now sort on `to` as of version `1.1.8`.  Let me know if you run into anything else :smile: 

Thanks for reporting!
