### ISSUE TITLE
Clarification: CasbahPersistenceJournaller#batchAppend

### ISSUE THREAD

**Issue by michaelom** [scullxbones/akka-persistence-mongo#90]
Hi Scullxbones,

I came across the following code snipped:

```
  private[mongodb] override def batchAppend(writes: ISeq[AtomicWrite])(implicit ec: ExecutionContext):Future[ISeq[Try[Unit]]] = Future {
    val batch = writes.map(write => Try(driver.serializeJournal(Atom[DBObject](write, driver.useLegacySerialization))))
    if (batch.forall(_.isSuccess)) {
      ...
      ...
    } else { // degraded performance, cant batch
      batch.map(_.map{serialized =>
        journal.insert(serialized)(identity, writeConcern)
        if(driver.realtimeEnablePersistence) realtime.insert(serialized)(identity, writeConcern)
      }.map(_ => ()))
    }
  }
```
Disclaimer: my Scala-skills are poor

My understanding is that this method is invoked if an event is passed into the `persist` method or if multiple events are passed into the `persistAll` method of a PersistentActor. The latter case is implemented as an atomic operation where you squeeze multiple events (and metadata) into a single document. The size of `ISeq[AtomicWrite] ` is then greater 1.
As I read this snipped, it seems documents are inserted even if serialisation fails for one or more`AtomicWrite`s. in the `ISeq`. So in case the serialisation of one event fails, documents are still written to MongoDB? 

Could you please clarify?

Mike

**Comment by scullxbones** [comment]
So the only way that there will be a batch size greater than one is if the `PersistentActor` uses `persistAsync` at a fast enough rate.  This was somewhat surprising, but @matheuslima clarified with the akka team and a documentation ticket was created.  I'm not sure what the status on that ticket is.  Using the batch `persist` does not cause a batch to show up for the plugin, that I have seen.

Yes that's correct, we do disregard documents that fail serialization and continue to persist the batch.  This is an attempt to implement the plugin interface as specified by the akka team, but it's possible that it's a better idea to assume that the user doesn't want anything persisted if any fail.  I need to think a bit more about that.  All that fail to serialize will show up in `onPersistRejected` which you can see described on the [persistence docs](http://doc.akka.io/docs/akka/2.4.0/scala/persistence.html).

**Comment by michaelom** [comment]
Hi scullxbones,
thanks for clarifying.

> So the only way that there will be a batch size greater than one is if the PersistentActor uses persistAsync at a fast enough rate.

That's my understanding too. In high throughput scenarios using `peristAsync` events can be buffered and send to `asyncWriteMessages(messages: immutable.Seq[AtomicWrite])`with a `seq`size greater 1 which then delegates to `akka.contrib.persistence.mongodb.MongoJournal#asyncWriteMessages`. 

> Yes that's correct, we do disregard documents that fail serialization and continue to persist the batch. This is an attempt to implement the plugin interface as specified by the akka team, but it's possible that it's a better idea to assume that the user doesn't want anything persisted if any fail.

As long as the persisted event does not show up during replay, it's not harmful. It would still pollute the journal but at least it won't cause any troubles in the application.  However, if it does show up during replay, then PersistentActor (or PersistentView) will fail to handle the event and never recover correctly. The corresponding `pid`(or `aggregateId`) will become unusable. That would be a bad to say at least. Haven't verified this yet but I will write a test tomorrow.

I read the documentation on `asyncWriteMessages`several times and concluded that it's poorly written and hard to understand. :-) But the spec seems pretty explizit about serialisation errors. 
I think the following paragraph applies for serialization errors:
>>>   
   The journal can also signal that it rejects individual messages (`AtomicWrite`) by
   the returned `immutable.Seq[Try[Unit]]`. The returned `Seq` must have as many elements
   as the input `messages` `Seq`. Each `Try` element signals if the corresponding
   `AtomicWrite` is rejected or not, with an exception describing the problem. Rejecting
   a message means it was not stored, i.e. it must not be included in a later replay.
   Rejecting a message is typically done before attempting to store it, e.g. because of
   serialization error.

There was a lot of discussion in the user group and on github, so maybe I missed something.

If you are uncertain about how to deal with this, a configurable property would be a good idea. Maybe I can submit a PR.

**Comment by scullxbones** [comment]
> As long as the persisted event does not show up during replay, it's not harmful. It would still pollute the journal but at least it won't cause any troubles in the application. However, if it does show up during replay, then PersistentActor (or PersistentView) will fail to handle the event and never recover correctly. The corresponding pid(or aggregateId) will become unusable. That would be bad to say at least. Haven't verified this yet but I will write a test tomorrow.

Based on your response, I'm not sure I was very clear.  If the event doesn't serialize it will *not be in the journal*.  We'll return a `Failure` to akka-persistence, which will raise the `onPersistRejected` to the offending `PersistentActor`.  Only successful serializations will make it to the mongo insert statement to be appended to the journal.  Which is (I think) exactly in line with your quote of the akka docs.

I'm fairly certain we're dealing with it in a consistent way, and given the behavior of batching in `persistAsync`, the failures could be unexpected were we to reject the entire batch at the first failure to serialize.  But it's worth discussing, no doubt.

**Comment by scullxbones** [comment]
So after testing a bit with this, it is clear I was playing fast and loose with terminology.  It's important to note that the plugin considers events at the `AtomicWrite` block level, not at the `Event` level.  

For simplicity, i'm going to only consider the case of a single active `PersistentActor`.  As I discovered, the case only gets stronger with the more common case of multiple active actors.  I've also assumed the simple case of choosing one of the four options for event storage in a given `case` of the `receiveCommand` method.  There are really four scenarios (corresponding to the four `persist` calls) for the plugin behavior as it stands today:

- `persist` (single event) will cause a `Seq[AtomicWrite]` of size 1 to show up at the plugin with a single event in the `AtomicWrite`. If serialization fails, nothing is persisted and `onPersistRejected` is called
- `persistAll` (batch) will cause a `Seq[AtomicWrite]` of size 1 to show up, with the batch of events in that `AtomicWrite`.  If serialization fails for any event, nothing is persisted and `onPersistRejected` is called for all of the events in the batch.
- `persistAsync` (single) will cause a `Seq[AtomicWrite]` of some size to show up at the plugin with one event in the `AtomicWrite`.  The grouping is performed by `akka-persistence` in this case and is a function of the current persistence load - higher load tends towards larger batches (`AtomicWrite`s).  If serialization fails, nothing is persisted in the shared `AtomicWrite`, and all events are sent to the `onPersistRejected` of the originating `PersistentActor`.  This does not mean any other `AtomicWrite`s with successful serialization will be rejected, they will be attempted to be stored.
- `persistAllAsync` (batch) will cause a `Seq[AtomicWrite]` of some size to show up at the the plugin with the batch of events together in one of the `AtomicWrite`s.  If serialization fails for any event in that batch, nothing is persisted and `onPersistRejected` is called for all the events in that `AtomicWrite`.  This will not affect any other `AtomicWrite`s in the `Seq`.

One other guarantee `akka-persistence` provides (which follows from above) is that every `AtomicWrite` has only events from a single `persistenceId`, a single `PersistentActor`.

Despite what I originally thought, `akka-persistence` will not combine individual calls, whether they are `persist` or `persistAsync` into a single `AtomicWrite`.  Combining writes is totally under control of the user's `PersistentActor` implementation.

So back to your question @michaelom:
>My understanding is that this method is invoked if an event is passed into the persist method or if multiple events are passed into the persistAll method of a PersistentActor. The latter case is implemented as an atomic operation where you squeeze multiple events (and metadata) into a single document. The size of ISeq[AtomicWrite] is then greater 1.

Waiting calls (`persist` and `persistBatch`) only cause a `ISeq[AtomicWrite]` of size 1.  The number of events in the `AtomicWrite` will be more than one only in the case of `persistBatch` used with a `Seq` of size > 1.  Only by using the "async" methods `persistAsync` and `persistAllAsync` can the `ISeq[AtomicWrite]` ever grow larger than one, and even in that case only under sufficient write load.

> As I read this snippet, it seems documents are inserted even if serialisation fails for one or moreAtomicWrites. in the ISeq. 

This reading is exactly right.

> So in case the serialisation of one event fails, documents are still written to MongoDB?

Yes, any time the `ISeq` has more than one `AtomicWrite` in it. But each `AtomicWrite` is a discrete, separate event, corresponding to a single invocation of `persist*` in the application.

So after the research and better understanding (or should I say re - understanding :smile:) of the plugin API and `akka-persistence` i'm confident that the original implementation is the right one.  Especially considering that in doing so, we could affect other `PersistentActor`s with different `persistenceId`s that have no issues with their serialization.

I'm not going to add a flag in (technically i'm going to undo the local work) to discard the rest of the `ISeq`.

Thanks for the question, it prompted me to dig deep into `akka-persistence` to figure out an answer, and I learned a lot!

**Comment by michaelom** [comment]
Thank you for the elaborate answer and for clearing up any concerns I had.

Now I feel like I understand the semantics for `persist` and `persistAsync`. :smiley:

**Comment by michaelom** [comment]
I did not mean to hit the close button. That's up to you. :-)

**Comment by scullxbones** [comment]
Ah - no problem.  Wanted to make sure you saw it before closing it.

Thanks again for the question!
