### ISSUE TITLE
Upgrade ReactiveMongo dependency to the latest version

### ISSUE THREAD

**Issue by alari** [scullxbones/akka-persistence-mongo#96]
Last release is 0.11.9.
In plugin v0.11.6 is used.
They are not binary compatible, so changing version leads to awful errors.

**Comment by scullxbones** [comment]
Hi @alari - this came up before in #83.  The binary compatibility break is kind of rough (on a minor especially), agreed.

I wanted to hold off until rxmongo 0.12.0 is released.  WDYT?

**Comment by alari** [comment]
Well, are they really going to release it soon?
If they do, it's okay to hold off.

**Comment by scullxbones** [comment]
I don't know, looking at [this list](https://github.com/ReactiveMongo/ReactiveMongo/milestones/0.12.0).  Most of those tickets have sat for a long time.  Maybe it's time. I do want to separate it from 2.4.2 compatibility though

**Comment by scullxbones** [comment]
I'll add this to the `1.2.0` release, which should be ready to go in the next couple days.

**Comment by scullxbones** [comment]
Added to `1.2.0` - thanks for the report!
